### Imports

In [1]:
import pandas as pd
import re
import os

In [2]:
BASE_DATA_PATH = '../Data/raw_data'

players_path = os.path.join(BASE_DATA_PATH, 'players.csv')
advanced_stats_all_seasons_path = os.path.join(BASE_DATA_PATH, 'advanced_stats_all_seasons.csv')
champion_players_all_seasons_path = os.path.join(BASE_DATA_PATH, 'champion_players_all_seasons.csv')
mvp_all_seasons_path = os.path.join(BASE_DATA_PATH, 'mvp_all_seasons.csv')

## Players

In [33]:
players_raw= pd.read_csv(players_path)

In [34]:
players_raw.shape

(5416, 24)

In [35]:
players_raw.columns

Index(['Unnamed: 0', 'player_id', 'full_name', 'birth_date', 'born', 'height',
       'weight', 'nationality', 'position', 'shoots', 'college', 'high_school',
       'career_length', 'link', 'G', 'PTS', 'AST', 'FG%', 'FT%', 'WS', 'TRB',
       'FG3%', 'eFG%', 'PER'],
      dtype='object')

In [36]:
players_raw.head(20)

,Unnamed: 0,player_id,full_name,birth_date,born,height,weight,nationality,position,shoots,...,G,PTS,AST,FG%,FT%,WS,TRB,FG3%,eFG%,PER
0,0,aubucch01,Chet Aubuchon,"May 18 , 1916","Gary, Indiana us",178,62.0,us,Guard,Right,...,30.0,2.2,0.7,25.3,54.3,1.2,NaN,NaN,NaN,NaN
1,1,willial06,Alondes Williams,"June 19 , 1999","Milwaukee , Wisconsin us",193,95.0,us,Shooting Guard,Right,...,13.0,4.2,1.0,55.6,88.9,0.2,2.1,31.6,63.9,15.1
2,2,barnhle01,Leo Barnhorst,"May 11 , 1924","Indianapolis, Indiana us",193,86.0,us,Small Forward,Right,...,344.0,9.4,3.2,36.8,66.5,13.3,5.4,NaN,NaN,14.2
3,3,morriis01,Isaiah Morris,"April 2 , 1969","Richmond, Virginia us",203,103.0,us,Small Forward,Right,...,25.0,2.2,0.2,45.6,75.0,0.0,0.5,NaN,45.6,10.6
4,4,jacksja01,Jaren Jackson,"October 27 , 1967","New Orleans, Louisiana us",193,86.0,us,Shooting Guard,Right,...,431.0,5.5,1.2,39.1,76.4,11.5,1.8,35.3,46.9,10.1
5,5,santogu01,Gui Santos,"June 22 , 2002","Brasilia, Brazil br",201,83.0,br,Power Forward,Right,...,147.0,6.4,1.7,49.0,73.7,5.2,3.3,34.7,57.8,13.5
6,6,gillan01,Anthony Gill,"October 17 , 1992","High Point, North Carolina us",201,104.0,us,Power Forward,Right,...,285.0,3.8,0.7,54.5,74.9,5.8,1.9,31.2,58.5,12.5
7,7,rhodege01,Gene Rhodes,"September 2 , 1927","St. Louis, Missouri us",185,77.0,us,Shooting Guard,Right,...,65.0,5.2,1.4,31.9,70.4,0.9,1.5,NaN,NaN,11.2
8,8,brownle02,Lewis Brown,"February 19 , 1955","Los Angeles, California us",211,102.0,us,Center,Left,...,2.0,1.0,0.0,0.0,40.0,-0.1,1.0,NaN,0.0,-18.6
9,9,hicksph01,Phil Hicks,"January 31 , 1953","Chicago, Illinois us",201,92.0,us,Small Forward,Right,...,57.0,2.3,0.6,44.7,77.8,0.5,1.6,NaN,NaN,11.0
10,10,harrija01,Jalen Harris,"August 14 , 1998","Dallas, Texas us",196,88.0,us,Shooting Guard,Right,...,13.0,7.4,1.3,50.0,77.8,0.3,1.4,47.2,61.8,15.2
11,11,dykerge01,Gene Dyker,"February 17 , 1930","Chicago, Illinois us",198,102.0,us,Forward,Right,...,11.0,1.5,0.5,23.1,50.0,-0.3,1.5,NaN,NaN,0.4
12,12,conlege01,Gene Conley,"November 10 , 1930","Muskogee, Oklahoma us",203,102.0,us,Power Forward,Right,...,351.0,5.9,0.6,37.1,65.7,5.1,6.3,NaN,NaN,10.2
13,13,longwi01,Willie Long,"March 1 , 1950","Fort Wayne, Indiana us",203,102.0,us,Power Forward and Small Forward,Right,...,213.0,11.4,1.0,42.1,77.4,6.9,6.0,0.0,42.1,13.1
14,14,hillsi01,Simmie Hill,"November 14 , 1946","Midland, Pennsylvania us",201,105.0,us,Small Forward,Right,...,252.0,9.7,1.3,43.2,76.3,6.9,5.3,29.3,44.0,11.4
15,15,pietrmi01,Mickaël Piétrus,"February 7 , 1982","Les Abymes, Guadeloupe gp",198,97.0,gp,"Small Forward, Shooting Guard, and Point Guard",Right,...,557.0,8.3,0.8,42.5,66.5,19.7,3.1,35.5,51.4,11.6
16,16,knighne01,Negele Knight,"March 6 , 1967","Detroit, Michigan us",185,79.0,us,Point Guard,Right,...,276.0,6.2,2.8,43.6,73.0,4.2,1.3,26.3,44.4,11.3
17,17,willidu01,Duck Williams,"August 2 , 1956","Demopolis, Alabama us",188,81.0,us,Point Guard,Right,...,77.0,6.6,2.4,44.7,70.0,-0.3,1.4,0.0,44.7,8.6
18,18,traorno01,Nolan Traoré,"May 28 , 2006","Créteil, France fr",190,83.0,fr,Point Guard,Right,...,56.0,8.9,3.8,38.0,78.7,-1.6,1.8,31.8,44.4,7.9
19,19,alexavi01,Victor Alexander,"August 31 , 1969","Detroit, Michigan us",206,120.0,us,Center,Right,...,286.0,8.9,0.9,51.8,63.4,8.8,4.8,28.6,52.2,13.7

In [37]:
players_raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5416 entries, 0 to 5415
Data columns (total 24 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Unnamed: 0     5416 non-null   int64
 1   player_id      5416 non-null   object
 2   full_name      5416 non-null   object
 3   birth_date     5412 non-null   object
 4   born           5412 non-null   object
 5   height         5416 non-null   int64
 6   weight         5411 non-null   float64
 7   nationality    5416 non-null   object
 8   position       5416 non-null   object
 9   shoots         5416 non-null   object
 10  college        5015 non-null   object
 11  high_school    4867 non-null   object
 12  career_length  4686 non-null   object
 13  link           5416 non-null   object
 14  G              5416 non-null   float64
 15  PTS            5416 non-null   float64
 16  AST            5416 non-null   float64
 17  FG%            5381 non-null   float64
 18  FT%            5164 non-null   float64
 19  WS             5415 non-null   float64
 20  TRB            5124 non-null   float64
 21  FG3%           3751 non-null   float64
 22  eFG%           4259 non-null   float64
 23  PER            5068 non-null   float64
dtypes: float64(11), int64(2), object(11)
memory usage: 1015.6+ KB

In [38]:
len(players_raw['position'].unique())

44

In [39]:
players_raw['position'].unique()

array(['Guard', 'Shooting Guard', 'Small Forward', 'Power Forward',
       'Center', 'Forward', 'Power Forward and Small Forward',
       'Small Forward, Shooting Guard, and Point Guard', 'Point Guard',
       'Small Forward and Power Forward',
       'Point Guard and Shooting Guard', 'Forward/Center',
       'Center and Power Forward', 'Shooting Guard and Small Forward',
       'Forward/Guard', 'Power Forward and Center',
       'Shooting Guard and Point Guard',
       'Small Forward and Shooting Guard',
       'Power Forward, Small Forward, and Center', 'Center/Forward',
       'Shooting Guard, Point Guard, and Small Forward',
       'Small Forward, Power Forward, and Shooting Guard',
       'Guard/Forward', 'Power Forward, Center, and Small Forward',
       'Center, Power Forward, and Small Forward',
       'Shooting Guard, Small Forward, and Point Guard',
       'Point Guard and Small Forward',
       'Small Forward, Shooting Guard, and Power Forward',
       'Small Forward and Point Guard', 'Small Forward and Center',
       'Power Forward and Shooting Guard',
       'Small Forward, Power Forward, and Center',
       'Power Forward, Small Forward, and Shooting Guard',
       'Power Forward, Shooting Guard, and Small Forward',
       'Shooting Guard, Small Forward, and Power Forward',
       'Power Forward, Center, Forward, and Small Forward',
       'Power Forward, Small Forward, Point Guard, and Shooting Guard',
       'Point Guard, Shooting Guard, Power Forward, and Small Forward',
       'Small Forward, Center, and Power Forward',
       'Point Guard, Shooting Guard, and Power Forward',
       'Point Guard, Small Forward, and Shooting Guard',
       'Small Forward, Power Forward, Point Guard, Center, and Shooting Guard',
       'Shooting Guard and Power Forward', 'Center and Small Forward'],
      dtype=object)

In [23]:
## position column needs Standardization

In [40]:
players_raw['shoots'].value_counts()

shoots
Right    5036
Left      380
Name: count, dtype: int64

In [41]:
## shoots needs standardization
## college has sevral values and I should split it

In [42]:
players_raw['nationality'].value_counts()

nationality
us    4781
ca      60
fr      49
au      35
de      30
      ...
no       1
hu       1
uy       1
ir       1
bg       1
Name: count, Length: 93, dtype: int64

In [43]:
players_raw['nationality'].unique()

array(['us', 'br', 'gp', 'fr', 'de', 'it', 'ru', 'lv', 'gh', 'ar', 'pl',
       'es', 'gb', 'sn', 'ng', 'gf', 'rs', 'mx', 'hr', 'jp', 'jm', 'il',
       'ch', 'lt', 'gr', 'nl', 'ua', 'ss', 'pa', 'do', 'ca', 'ga', 'cm',
       'au', 'bs', 'si', 'cz', 'ee', 'ht', 'tr', 'cn', 'cd', 'ml', 'gn',
       'mk', 'sd', 'bg', 'ag', 'ir', 'no', 'tz', 'kr', 'cg', 'ie', 'ba',
       'za', 'cu', 'me', 'lb', 'vg', 'uz', 'is', 'pt', 'nz', 'tw', 'se',
       'tn', 'eg', 'dk', 'vc', 'pr', 'hu', 'uy', 'be', 'ge', 'sk', 'gy',
       'ro', 'vi', 'ni', 'mq', 'cy', 'cv', 'fi', 'dm', 'lc', 'co', 'at',
       'lu', 'ma', 've', 'ao', 'tt'], dtype=object)

### cleaning and standardization Players raw data

In [44]:
players = players_raw.drop(columns=["Unnamed: 0"])

In [45]:
players["birth_date"].head(20).apply(repr)

0          'May 18 , 1916'
1         'June 19 , 1999'
2          'May 11 , 1924'
3         'April 2 , 1969'
4      'October 27 , 1967'
5         'June 22 , 2002'
6      'October 17 , 1992'
7     'September 2 , 1927'
8     'February 19 , 1955'
9      'January 31 , 1953'
10      'August 14 , 1998'
11    'February 17 , 1930'
12    'November 10 , 1930'
13        'March 1 , 1950'
14    'November 14 , 1946'
15     'February 7 , 1982'
16        'March 6 , 1967'
17       'August 2 , 1956'
18         'May 28 , 2006'
19      'August 31 , 1969'
Name: birth_date, dtype: object

In [29]:
## converting birthdate format to datetime

In [46]:
players["birth_date"] = (
    players["birth_date"]
    .str.replace(r"\s*,\s*", ", ", regex=True)
)

players["birth_date"] = pd.to_datetime(
    players["birth_date"],
    format="%B %d, %Y",
    errors="coerce"
)

In [53]:
players.head(10)

,player_id,full_name,birth_date,born,height,weight,nationality,position,shoots,college,...,G,PTS,AST,FG%,FT%,WS,TRB,FG3%,eFG%,PER
0,aubucch01,Chet Aubuchon,1916-05-18,"Gary, Indiana us",178,62.0,us,[G],Right,Michigan State,...,30.0,2.2,0.7,25.3,54.3,1.2,NaN,NaN,NaN,NaN
1,willial06,Alondes Williams,1999-06-19,"Milwaukee , Wisconsin us",193,95.0,us,[SG],Right,"Colleges: Triton College , Oklahoma , Wake Forest",...,13.0,4.2,1.0,55.6,88.9,0.2,2.1,31.6,63.9,15.1
2,barnhle01,Leo Barnhorst,1924-05-11,"Indianapolis, Indiana us",193,86.0,us,[SF],Right,Notre Dame,...,344.0,9.4,3.2,36.8,66.5,13.3,5.4,NaN,NaN,14.2
3,morriis01,Isaiah Morris,1969-04-02,"Richmond, Virginia us",203,103.0,us,[SF],Right,Arkansas,...,25.0,2.2,0.2,45.6,75.0,0.0,0.5,NaN,45.6,10.6
4,jacksja01,Jaren Jackson,1967-10-27,"New Orleans, Louisiana us",193,86.0,us,[SG],Right,Georgetown,...,431.0,5.5,1.2,39.1,76.4,11.5,1.8,35.3,46.9,10.1
5,santogu01,Gui Santos,2002-06-22,"Brasilia, Brazil br",201,83.0,br,[PF],Right,NaN,...,147.0,6.4,1.7,49.0,73.7,5.2,3.3,34.7,57.8,13.5
6,gillan01,Anthony Gill,1992-10-17,"High Point, North Carolina us",201,104.0,us,[PF],Right,"Colleges: South Carolina , Virginia",...,285.0,3.8,0.7,54.5,74.9,5.8,1.9,31.2,58.5,12.5
7,rhodege01,Gene Rhodes,1927-09-02,"St. Louis, Missouri us",185,77.0,us,[SG],Right,Western Kentucky,...,65.0,5.2,1.4,31.9,70.4,0.9,1.5,NaN,NaN,11.2
8,brownle02,Lewis Brown,1955-02-19,"Los Angeles, California us",211,102.0,us,[C],Left,UNLV,...,2.0,1.0,0.0,0.0,40.0,-0.1,1.0,NaN,0.0,-18.6
9,hicksph01,Phil Hicks,1953-01-31,"Chicago, Illinois us",201,92.0,us,[SF],Right,Tulane,...,57.0,2.3,0.6,44.7,77.8,0.5,1.6,NaN,NaN,11.0

In [19]:
## position column standardization

In [49]:
position_map = {
    "Point Guard": "PG",
    "Shooting Guard": "SG",
    "Small Forward": "SF",
    "Power Forward": "PF",
    "Center": "C",
    "Guard": "G",
    "Forward": "F"
}

In [50]:
def normalize_positions(pos):

    if pd.isna(pos):
        return None

    parts = re.split(r",| and |/", pos)

    positions = []

    for part in parts:
        part = part.strip()

        if part in position_map:
            positions.append(position_map[part])

    return sorted(set(positions))

In [52]:
players["position"] = players["position"].apply(normalize_positions)

TypeError: expected string or bytes-like object

In [ ]:
## shoots column standardization

In [54]:
shoot_map = {"Right": "Right",
             "Left": "Left",
             "LeftRight": "Both",
             "RightLeft": "Both"}

players["shoots"] = players["shoots"].replace(shoot_map)

In [55]:
players.head()

,player_id,full_name,birth_date,born,height,weight,nationality,position,shoots,college,...,G,PTS,AST,FG%,FT%,WS,TRB,FG3%,eFG%,PER
0,aubucch01,Chet Aubuchon,1916-05-18,"Gary, Indiana us",178,62.0,us,[G],Right,Michigan State,...,30.0,2.2,0.7,25.3,54.3,1.2,NaN,NaN,NaN,NaN
1,willial06,Alondes Williams,1999-06-19,"Milwaukee , Wisconsin us",193,95.0,us,[SG],Right,"Colleges: Triton College , Oklahoma , Wake Forest",...,13.0,4.2,1.0,55.6,88.9,0.2,2.1,31.6,63.9,15.1
2,barnhle01,Leo Barnhorst,1924-05-11,"Indianapolis, Indiana us",193,86.0,us,[SF],Right,Notre Dame,...,344.0,9.4,3.2,36.8,66.5,13.3,5.4,NaN,NaN,14.2
3,morriis01,Isaiah Morris,1969-04-02,"Richmond, Virginia us",203,103.0,us,[SF],Right,Arkansas,...,25.0,2.2,0.2,45.6,75.0,0.0,0.5,NaN,45.6,10.6
4,jacksja01,Jaren Jackson,1967-10-27,"New Orleans, Louisiana us",193,86.0,us,[SG],Right,Georgetown,...,431.0,5.5,1.2,39.1,76.4,11.5,1.8,35.3,46.9,10.1

In [56]:
players.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5416 entries, 0 to 5415
Data columns (total 23 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   player_id      5416 non-null   object
 1   full_name      5416 non-null   object
 2   birth_date     5403 non-null   datetime64[ns]
 3   born           5412 non-null   object
 4   height         5416 non-null   int64
 5   weight         5411 non-null   float64
 6   nationality    5416 non-null   object
 7   position       5416 non-null   object
 8   shoots         5416 non-null   object
 9   college        5015 non-null   object
 10  high_school    4867 non-null   object
 11  career_length  4686 non-null   object
 12  link           5416 non-null   object
 13  G              5416 non-null   float64
 14  PTS            5416 non-null   float64
 15  AST            5416 non-null   float64
 16  FG%            5381 non-null   float64
 17  FT%            5164 non-null   float64
 18  WS             5415 non-null   float64
 19  TRB            5124 non-null   float64
 20  FG3%           3751 non-null   float64
 21  eFG%           4259 non-null   float64
 22  PER            5068 non-null   float64
dtypes: datetime64[ns](1), float64(11), int64(1), object(10)
memory usage: 973.3+ KB

## Advanced_stats_all_rows

In [57]:
adv_rows_raw = pd.read_csv(advanced_stats_all_seasons_path)

In [58]:
adv_rows_raw.shape

(3936, 14)

In [59]:
adv_rows_raw.head(10)

,season,player_id,player_name,player_url,age,team,position,games,games_started,minutes,win_shares,ws_per_48,bpm,vorp
0,2019-20,hardeja01,James Harden,https://www.basketball-reference.com/players/h...,30,HOU,SG,68,68,2483,13.1,0.254,9.6,7.3
1,2019-20,lillada01,Damian Lillard,https://www.basketball-reference.com/players/l...,29,POR,PG,66,66,2474,11.6,0.225,7.5,5.9
2,2019-20,antetgi01,Giannis Antetokounmpo,https://www.basketball-reference.com/players/a...,25,MIL,PF,63,63,1917,11.1,0.279,11.5,6.6
3,2019-20,davisan02,Anthony Davis,https://www.basketball-reference.com/players/d...,26,LAL,PF,62,62,2131,11.1,0.250,8.0,5.4
4,2019-20,goberru01,Rudy Gobert,https://www.basketball-reference.com/players/g...,27,UTA,C,68,68,2333,10.7,0.221,3.6,3.3
5,2019-20,jamesle01,LeBron James,https://www.basketball-reference.com/players/j...,35,LAL,PG,67,67,2316,9.8,0.204,8.4,6.1
6,2019-20,jokicni01,Nikola Jokić,https://www.basketball-reference.com/players/j...,24,DEN,C,73,73,2336,9.8,0.202,7.4,5.5
7,2019-20,butleji01,Jimmy Butler,https://www.basketball-reference.com/players/b...,30,MIA,SF,58,58,1959,9.0,0.221,5.4,3.7
8,2019-20,paulch01,Chris Paul,https://www.basketball-reference.com/players/p...,34,OKC,PG,70,70,2208,8.9,0.193,4.4,3.5
9,2019-20,doncilu01,Luka Dončić,https://www.basketball-reference.com/players/d...,20,DAL,PG,61,61,2047,8.8,0.207,8.4,5.4

In [60]:
adv_rows_raw.columns

Index(['season', 'player_id', 'player_name', 'player_url', 'age', 'team',
       'position', 'games', 'games_started', 'minutes', 'win_shares',
       'ws_per_48', 'bpm', 'vorp'],
      dtype='object')

In [61]:
adv_rows_raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3936 entries, 0 to 3935
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   season         3936 non-null   object
 1   player_id      3936 non-null   object
 2   player_name    3936 non-null   object
 3   player_url     3936 non-null   object
 4   age            3936 non-null   int64
 5   team           3936 non-null   object
 6   position       3936 non-null   object
 7   games          3936 non-null   int64
 8   games_started  3936 non-null   int64
 9   minutes        3936 non-null   int64
 10  win_shares     3936 non-null   float64
 11  ws_per_48      3936 non-null   float64
 12  bpm            3936 non-null   float64
 13  vorp           3936 non-null   float64
dtypes: float64(4), int64(4), object(6)
memory usage: 430.6+ KB

In [62]:
adv_rows_raw['position'].unique()

array(['SG', 'PG', 'PF', 'C', 'SF'], dtype=object)

In [63]:
adv_rows_raw['position'].value_counts()

position
SG    983
PF    760
SF    755
C     737
PG    701
Name: count, dtype: int64

In [64]:
adv_rows_raw['season'].unique()

array(['2019-20', '2020-21', '2021-22', '2022-23', '2023-24', '2024-25',
       '2025-26'], dtype=object)

## Champion players all seasons

In [65]:
champ_seasons_raw = pd.read_csv(champion_players_all_seasons_path)

In [66]:
champ_seasons_raw.shape

(115, 18)

In [67]:
champ_seasons_raw.head()

,season,champion_team,team_code,player_id,player_name,player_url,number,position,height,weight,birth_date,birth_place,experience,college,age,games,minutes,win_shares
0,2020-21,Milwaukee Bucks,MIL,adamsja01,Jaylen Adams,https://www.basketball-reference.com/players/a...,6,PG,6-0,225,1996-05-04,us US,2,St. Bonaventure,24,7,18,-0.1
1,2020-21,Milwaukee Bucks,MIL,antetgi01,Giannis Antetokounmpo,https://www.basketball-reference.com/players/a...,34,PF,6-11,243,1994-12-06,gr GR,7,NaN,26,61,2013,10.2
2,2020-21,Milwaukee Bucks,MIL,antetth01,Thanasis Antetokounmpo,https://www.basketball-reference.com/players/a...,43,SF,6-7,219,1992-07-18,gr GR,2,NaN,28,57,551,0.7
3,2020-21,Milwaukee Bucks,MIL,augusdj01,D.J. Augustin,https://www.basketball-reference.com/players/a...,12,PG,5-11,183,1987-11-10,us US,12,Texas,33,57,1129,2.1
4,2020-21,Milwaukee Bucks,MIL,bryanel01,Elijah Bryant,https://www.basketball-reference.com/players/b...,3,SG,6-5,210,1995-04-19,us US,R,"Elon University , BYU",25,1,32,0.0

In [68]:
champ_seasons_raw.columns

Index(['season', 'champion_team', 'team_code', 'player_id', 'player_name',
       'player_url', 'number', 'position', 'height', 'weight', 'birth_date',
       'birth_place', 'experience', 'college', 'age', 'games', 'minutes',
       'win_shares'],
      dtype='object')

In [69]:
champ_seasons_raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 115 entries, 0 to 114
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   season         115 non-null    object
 1   champion_team  115 non-null    object
 2   team_code      115 non-null    object
 3   player_id      115 non-null    object
 4   player_name    115 non-null    object
 5   player_url     115 non-null    object
 6   number         115 non-null    int64
 7   position       115 non-null    object
 8   height         115 non-null    object
 9   weight         115 non-null    int64
 10  birth_date     115 non-null    object
 11  birth_place    115 non-null    object
 12  experience     115 non-null    object
 13  college        100 non-null    object
 14  age            115 non-null    int64
 15  games          115 non-null    int64
 16  minutes        115 non-null    int64
 17  win_shares     115 non-null    float64
dtypes: float64(1), int64(5), object(12)
memory usage: 16.3+ KB

In [70]:
champ_seasons_raw['champion_team'].value_counts()

champion_team
Milwaukee Bucks          22
New York Knicks          20
Boston Celtics           19
Oklahoma City Thunder    19
Denver Nuggets           18
Golden State Warriors    17
Name: count, dtype: int64

In [71]:
champions = champ_seasons_raw.copy()

In [72]:
champions.shape

(115, 18)

In [73]:
champions.head()

,season,champion_team,team_code,player_id,player_name,player_url,number,position,height,weight,birth_date,birth_place,experience,college,age,games,minutes,win_shares
0,2020-21,Milwaukee Bucks,MIL,adamsja01,Jaylen Adams,https://www.basketball-reference.com/players/a...,6,PG,6-0,225,1996-05-04,us US,2,St. Bonaventure,24,7,18,-0.1
1,2020-21,Milwaukee Bucks,MIL,antetgi01,Giannis Antetokounmpo,https://www.basketball-reference.com/players/a...,34,PF,6-11,243,1994-12-06,gr GR,7,NaN,26,61,2013,10.2
2,2020-21,Milwaukee Bucks,MIL,antetth01,Thanasis Antetokounmpo,https://www.basketball-reference.com/players/a...,43,SF,6-7,219,1992-07-18,gr GR,2,NaN,28,57,551,0.7
3,2020-21,Milwaukee Bucks,MIL,augusdj01,D.J. Augustin,https://www.basketball-reference.com/players/a...,12,PG,5-11,183,1987-11-10,us US,12,Texas,33,57,1129,2.1
4,2020-21,Milwaukee Bucks,MIL,bryanel01,Elijah Bryant,https://www.basketball-reference.com/players/b...,3,SG,6-5,210,1995-04-19,us US,R,"Elon University , BYU",25,1,32,0.0

## MVP

In [74]:
mvp_all_seasons_raw = pd.read_csv(mvp_all_seasons_path)

In [75]:
mvp_all_seasons_raw.shape

(81, 7)

In [76]:
mvp_all_seasons_raw.head()

,season,mvp_rank,player_id,player_name,player_url,team,mvp_share
0,2019-20,1,antetgi01,Giannis Antetokounmpo,/players/a/antetgi01.html,MIL,0.952
1,2019-20,2,jamesle01,LeBron James,/players/j/jamesle01.html,LAL,0.746
2,2019-20,3,hardeja01,James Harden,/players/h/hardeja01.html,HOU,0.363
3,2019-20,4,doncilu01,Luka Dončić,/players/d/doncilu01.html,DAL,0.198
4,2019-20,5,leonaka01,Kawhi Leonard,/players/l/leonaka01.html,LAC,0.166

In [77]:
mvp_all_seasons_raw['season'].value_counts()

season
2020-21    15
2022-23    13
2019-20    12
2021-22    12
2024-25    12
2023-24     9
2025-26     8
Name: count, dtype: int64

In [78]:
mvp_all_seasons_raw['team'].value_counts()

team
DEN    7
MIL    6
BOS    6
LAL    6
DAL    5
OKC    5
CLE    4
NYK    4
GSW    4
PHI    4
PHO    4
LAC    4
SAC    3
MIA    2
POR    2
TOT    2
MEM    2
MIN    2
DET    2
TOR    1
UTA    1
WAS    1
CHI    1
BRK    1
HOU    1
SAS    1
Name: count, dtype: int64

In [79]:
mvp_all_seasons_raw['player_name'].value_counts()

player_name
Nikola Jokić               7
Giannis Antetokounmpo      6
Luka Dončić                6
Jayson Tatum               5
Stephen Curry              4
Shai Gilgeous-Alexander    4
LeBron James               4
Donovan Mitchell           3
Jalen Brunson              3
Joel Embiid                3
Kawhi Leonard              3
James Harden               3
Chris Paul                 3
Jimmy Butler               2
Cade Cunningham            2
Anthony Edwards            2
Damian Lillard             2
Domantas Sabonis           2
Ja Morant                  2
Kevin Durant               2
Evan Mobley                1
Victor Wembanyama          1
De'Aaron Fox               1
Rudy Gobert                1
DeMar DeRozan              1
Devin Booker               1
Ben Simmons                1
Russell Westbrook          1
Derrick Rose               1
Julius Randle              1
Pascal Siakam              1
Anthony Davis              1
Jaylen Brown               1
Name: count, dtype: int64

In [80]:
len(mvp_all_seasons_raw['player_name'].unique())

33

In [81]:
mvp_all_seasons_raw['team'].value_counts()

team
DEN    7
MIL    6
BOS    6
LAL    6
DAL    5
OKC    5
CLE    4
NYK    4
GSW    4
PHI    4
PHO    4
LAC    4
SAC    3
MIA    2
POR    2
TOT    2
MEM    2
MIN    2
DET    2
TOR    1
UTA    1
WAS    1
CHI    1
BRK    1
HOU    1
SAS    1
Name: count, dtype: int64

In [83]:
mvp_all_seasons_raw.isna().sum()

season         0
mvp_rank       0
player_id      0
player_name    0
player_url     0
team           0
mvp_share      0
dtype: int64

## Creating DataFrames

### Players DataFrame

In [84]:
players.head()

,player_id,full_name,birth_date,born,height,weight,nationality,position,shoots,college,...,G,PTS,AST,FG%,FT%,WS,TRB,FG3%,eFG%,PER
0,aubucch01,Chet Aubuchon,1916-05-18,"Gary, Indiana us",178,62.0,us,[G],Right,Michigan State,...,30.0,2.2,0.7,25.3,54.3,1.2,NaN,NaN,NaN,NaN
1,willial06,Alondes Williams,1999-06-19,"Milwaukee , Wisconsin us",193,95.0,us,[SG],Right,"Colleges: Triton College , Oklahoma , Wake Forest",...,13.0,4.2,1.0,55.6,88.9,0.2,2.1,31.6,63.9,15.1
2,barnhle01,Leo Barnhorst,1924-05-11,"Indianapolis, Indiana us",193,86.0,us,[SF],Right,Notre Dame,...,344.0,9.4,3.2,36.8,66.5,13.3,5.4,NaN,NaN,14.2
3,morriis01,Isaiah Morris,1969-04-02,"Richmond, Virginia us",203,103.0,us,[SF],Right,Arkansas,...,25.0,2.2,0.2,45.6,75.0,0.0,0.5,NaN,45.6,10.6
4,jacksja01,Jaren Jackson,1967-10-27,"New Orleans, Louisiana us",193,86.0,us,[SG],Right,Georgetown,...,431.0,5.5,1.2,39.1,76.4,11.5,1.8,35.3,46.9,10.1

In [85]:
player_df = players[
    ["player_id",
     "full_name",
     "birth_date",
      "born",
      "height",
      "weight",
      "shoots",
      "link"]].copy()

player_df.rename(columns={
    "born": "birth_place",
    "height": "height_cm",
    "weight": "weight_kg",
    "link": "player_url"
}, inplace=True)

In [86]:
player_df.head()

,player_id,full_name,birth_date,birth_place,height_cm,weight_kg,shoots,player_url
0,aubucch01,Chet Aubuchon,1916-05-18,"Gary, Indiana us",178,62.0,Right,https://www.basketball-reference.com/players/a...
1,willial06,Alondes Williams,1999-06-19,"Milwaukee , Wisconsin us",193,95.0,Right,https://www.basketball-reference.com/players/w...
2,barnhle01,Leo Barnhorst,1924-05-11,"Indianapolis, Indiana us",193,86.0,Right,https://www.basketball-reference.com/players/b...
3,morriis01,Isaiah Morris,1969-04-02,"Richmond, Virginia us",203,103.0,Right,https://www.basketball-reference.com/players/m...
4,jacksja01,Jaren Jackson,1967-10-27,"New Orleans, Louisiana us",193,86.0,Right,https://www.basketball-reference.com/players/j...

### Country DataFrame

In [87]:
len(players['nationality'].unique())

93

In [88]:
country_df = (
    players[["nationality"]]
    .dropna()
    .drop_duplicates()
    .sort_values("nationality")
    .reset_index(drop=True))

In [89]:
country_df.insert(0, "country_id", range(1, len(country_df) + 1))

In [90]:
country_df.rename(columns={
    "nationality": "country_code"}, inplace=True)

In [91]:
country_df.head()

   country_id country_code
0           1           ag
1           2           ao
2           3           ar
3           4           at
4           5           au

In [92]:
country_df.shape

(93, 2)

In [93]:
## adding country_id as a foreign key to players_df

In [94]:
country_map = dict(zip(
        country_df["country_code"],
        country_df["country_id"]))

In [95]:
player_df["country_id"] = players["nationality"].map(country_map)

In [96]:
player_df.head()

,player_id,full_name,birth_date,birth_place,height_cm,weight_kg,shoots,player_url,country_id
0,aubucch01,Chet Aubuchon,1916-05-18,"Gary, Indiana us",178,62.0,Right,https://www.basketball-reference.com/players/a...,86
1,willial06,Alondes Williams,1999-06-19,"Milwaukee , Wisconsin us",193,95.0,Right,https://www.basketball-reference.com/players/w...,86
2,barnhle01,Leo Barnhorst,1924-05-11,"Indianapolis, Indiana us",193,86.0,Right,https://www.basketball-reference.com/players/b...,86
3,morriis01,Isaiah Morris,1969-04-02,"Richmond, Virginia us",203,103.0,Right,https://www.basketball-reference.com/players/m...,86
4,jacksja01,Jaren Jackson,1967-10-27,"New Orleans, Louisiana us",193,86.0,Right,https://www.basketball-reference.com/players/j...,86

### college DataFrame

In [97]:
def parse_colleges(college):
    if pd.isna(college):
        return []

    # rmeving college 
    college = college.replace("Colleges:", "")

    
    colleges = college.split(",")

    # removing extra soaces
    colleges = [c.strip() for c in colleges]

    # removing empty strings
    colleges = [c for c in colleges if c]

    return colleges

In [98]:
all_colleges = []

for colleges in players["college"]:
    all_colleges.extend(parse_colleges(colleges))

In [99]:
college_df = pd.DataFrame({
    "college_name": sorted(set(all_colleges))})

In [100]:
college_df.insert(
    0,
    "college_id",
    range(1, len(college_df)+1))

In [101]:
college_df.head()

   college_id            college_name
0           1    1985 in College Park
1           2       Acadia University
2           3               Air Force
3           4                 Alabama
4           5  Alabama A&M University

In [102]:
college_df.shape

(670, 2)

### player_college DataFrame

In [103]:
# mapping college to each player

In [104]:
college_map = dict(
    zip(
        college_df["college_name"],
        college_df["college_id"]))

In [105]:
player_college_rows = []

for _, row in players.iterrows():

    colleges = parse_colleges(row["college"])

    for college in colleges:

        player_college_rows.append({
            "player_id": row["player_id"],
            "college_id": college_map[college]})

In [106]:
player_college_df = pd.DataFrame(player_college_rows)

In [107]:
player_college_df.drop_duplicates(inplace=True)

In [108]:
player_college_df.head()

   player_id  college_id
0  aubucch01         326
1  willial06         538
2  willial06         407
3  willial06         623
4  barnhle01         398

In [109]:
player_college_df.shape

(5751, 2)

### position DataFrame

In [110]:
all_positions = []

for positions in players["position"]:
    if positions:
        all_positions.extend(positions)

In [111]:
position_df = pd.DataFrame({
    "position_code": sorted(set(all_positions))})

In [112]:
position_df.insert(0,
            "position_id",
            range(1, len(position_df) + 1))

In [113]:
position_df.head()

   position_id position_code
0            1             C
1            2             F
2            3             G
3            4            PF
4            5            PG

In [114]:
position_df.shape

(7, 2)

### player_position DataFrame

In [115]:
position_map = dict(
    zip(
        position_df["position_code"],
        position_df["position_id"]
    )
)

In [116]:
player_position_rows = []

for _, row in players.iterrows():

    positions = row["position"]

    if not positions:
        continue

    for position in positions:

        player_position_rows.append({
            "player_id": row["player_id"],
            "position_id": position_map[position]})

In [117]:
player_position_df = pd.DataFrame(player_position_rows)

In [118]:
player_position_df.drop_duplicates(inplace=True)

In [119]:
player_position_df.head()

   player_id  position_id
0  aubucch01            3
1  willial06            7
2  barnhle01            6
3  morriis01            6
4  jacksja01            7

In [120]:
player_position_df.shape

(7156, 2)

### season DataFrame

In [121]:
season_df = (
    adv_rows_raw[["season"]]
    .drop_duplicates()
    .sort_values("season")
    .reset_index(drop=True))

In [122]:
season_df.insert(
    0,
    "season_id",
    range(1, len(season_df)+1))

In [123]:
season_df.rename(columns={
    "season": "season_name"}, inplace=True)

In [150]:
season_df

   season_id season_name
0          1     2019-20
1          2     2020-21
2          3     2021-22
3          4     2022-23
4          5     2023-24
5          6     2024-25
6          7     2025-26

### player_season_stats DataFrame

In [125]:
season_map = dict(
    zip(
        season_df["season_name"],
        season_df["season_id"]))

In [126]:
player_season_stats_df = adv_rows_raw[[
        "player_id",
        "team",
        "age",
        "games",
        "games_started",
        "minutes",
        "win_shares",
        "ws_per_48",
        "bpm",
        "vorp"
    ]
].copy()

In [127]:
player_season_stats_df["season_id"] = (adv_rows_raw["season"].map(season_map))

In [128]:
player_season_stats_df = player_season_stats_df[[
        "player_id",
        "season_id",
        "team",
        "age",
        "games",
        "games_started",
        "minutes",
        "win_shares",
        "ws_per_48",
        "bpm",
        "vorp"]]

In [129]:
player_season_stats_df.rename(columns={
    "team": "team_code"
}, inplace=True)

In [130]:
player_season_stats_df.head()

,player_id,season_id,team_code,age,games,games_started,minutes,win_shares,ws_per_48,bpm,vorp
0,hardeja01,1,HOU,30,68,68,2483,13.1,0.254,9.6,7.3
1,lillada01,1,POR,29,66,66,2474,11.6,0.225,7.5,5.9
2,antetgi01,1,MIL,25,63,63,1917,11.1,0.279,11.5,6.6
3,davisan02,1,LAL,26,62,62,2131,11.1,0.250,8.0,5.4
4,goberru01,1,UTA,27,68,68,2333,10.7,0.221,3.6,3.3

In [131]:
player_season_stats_df.shape

(3936, 11)

### team DataFrame

In [151]:
adv_rows_raw.head()

,season,player_id,player_name,player_url,age,team,position,games,games_started,minutes,win_shares,ws_per_48,bpm,vorp
0,2019-20,hardeja01,James Harden,https://www.basketball-reference.com/players/h...,30,HOU,SG,68,68,2483,13.1,0.254,9.6,7.3
1,2019-20,lillada01,Damian Lillard,https://www.basketball-reference.com/players/l...,29,POR,PG,66,66,2474,11.6,0.225,7.5,5.9
2,2019-20,antetgi01,Giannis Antetokounmpo,https://www.basketball-reference.com/players/a...,25,MIL,PF,63,63,1917,11.1,0.279,11.5,6.6
3,2019-20,davisan02,Anthony Davis,https://www.basketball-reference.com/players/d...,26,LAL,PF,62,62,2131,11.1,0.250,8.0,5.4
4,2019-20,goberru01,Rudy Gobert,https://www.basketball-reference.com/players/g...,27,UTA,C,68,68,2333,10.7,0.221,3.6,3.3

In [152]:
adv_rows_raw['team'].unique()

array(['HOU', 'POR', 'MIL', 'LAL', 'UTA', 'DEN', 'MIA', 'OKC', 'DAL',
       'LAC', 'BRK', 'PHO', 'TOR', 'IND', 'SAS', 'MEM', 'PHI', 'BOS',
       'NYK', 'ORL', 'ATL', 'SAC', 'WAS', 'NOP', 'MIN', 'DET', '2TM',
       'CHI', 'CLE', 'CHO', 'GSW', '3TM', '4TM'], dtype=object)

In [153]:
len(adv_rows_raw['team'].unique())

33

In [154]:
champ_seasons_raw['team_code'].unique()

array(['MIL', 'GSW', 'DEN', 'BOS', 'OKC', 'NYK'], dtype=object)

In [155]:
team_df = (adv_rows_raw[["team"]]
            .drop_duplicates()
            .rename(columns={"team": "team_code"})
            .sort_values("team_code")
            .reset_index(drop=True))

In [156]:
team_df

   team_code
0        2TM
1        3TM
2        4TM
3        ATL
4        BOS
5        BRK
6        CHI
7        CHO
8        CLE
9        DAL
10       DEN
11       DET
12       GSW
13       HOU
14       IND
15       LAC
16       LAL
17       MEM
18       MIA
19       MIL
20       MIN
21       NOP
22       NYK
23       OKC
24       ORL
25       PHI
26       PHO
27       POR
28       SAC
29       SAS
30       TOR
31       UTA
32       WAS

### mvp_awards DataFrame

In [138]:
mvp_all_seasons_raw.head()

,season,mvp_rank,player_id,player_name,player_url,team,mvp_share
0,2019-20,1,antetgi01,Giannis Antetokounmpo,/players/a/antetgi01.html,MIL,0.952
1,2019-20,2,jamesle01,LeBron James,/players/j/jamesle01.html,LAL,0.746
2,2019-20,3,hardeja01,James Harden,/players/h/hardeja01.html,HOU,0.363
3,2019-20,4,doncilu01,Luka Dončić,/players/d/doncilu01.html,DAL,0.198
4,2019-20,5,leonaka01,Kawhi Leonard,/players/l/leonaka01.html,LAC,0.166

In [157]:
mvp_all_seasons_raw.shape

(81, 7)

In [158]:
mvp_awards = mvp_all_seasons_raw.copy()

In [159]:
mvp_awards.rename(columns={
    "team": "team_code"}, inplace=True)

In [160]:
mvp_awards["season_id"] = (
    mvp_awards["season"]
    .map(season_map))

In [161]:
mvp_awards.shape

(81, 8)

In [162]:
mvp_award_df = mvp_awards[[
        "player_id",
        "season_id",
        "team_code",
        "mvp_rank",
        "mvp_share"]].copy()

In [163]:
mvp_awards.head()

,season,mvp_rank,player_id,player_name,player_url,team_code,mvp_share,season_id
0,2019-20,1,antetgi01,Giannis Antetokounmpo,/players/a/antetgi01.html,MIL,0.952,1
1,2019-20,2,jamesle01,LeBron James,/players/j/jamesle01.html,LAL,0.746,1
2,2019-20,3,hardeja01,James Harden,/players/h/hardeja01.html,HOU,0.363,1
3,2019-20,4,doncilu01,Luka Dončić,/players/d/doncilu01.html,DAL,0.198,1
4,2019-20,5,leonaka01,Kawhi Leonard,/players/l/leonaka01.html,LAC,0.166,1

In [164]:
mvp_award_df = mvp_award_df.drop(columns=["team_code"])

In [165]:
mvp_award_df.head()

   player_id  season_id  mvp_rank  mvp_share
0  antetgi01          1         1      0.952
1  jamesle01          1         2      0.746
2  hardeja01          1         3      0.363
3  doncilu01          1         4      0.198
4  leonaka01          1         5      0.166

In [166]:
mvp_award_df.isnull().sum()

player_id    0
season_id    0
mvp_rank     0
mvp_share    0
dtype: int64

In [167]:
mvp_award_df['season_id'].unique()

array([1, 2, 3, 4, 5, 6, 7], dtype=int64)

### champion_team_player DataFrame

In [168]:
champions.head()

,season,champion_team,team_code,player_id,player_name,player_url,number,position,height,weight,birth_date,birth_place,experience,college,age,games,minutes,win_shares
0,2020-21,Milwaukee Bucks,MIL,adamsja01,Jaylen Adams,https://www.basketball-reference.com/players/a...,6,PG,6-0,225,1996-05-04,us US,2,St. Bonaventure,24,7,18,-0.1
1,2020-21,Milwaukee Bucks,MIL,antetgi01,Giannis Antetokounmpo,https://www.basketball-reference.com/players/a...,34,PF,6-11,243,1994-12-06,gr GR,7,NaN,26,61,2013,10.2
2,2020-21,Milwaukee Bucks,MIL,antetth01,Thanasis Antetokounmpo,https://www.basketball-reference.com/players/a...,43,SF,6-7,219,1992-07-18,gr GR,2,NaN,28,57,551,0.7
3,2020-21,Milwaukee Bucks,MIL,augusdj01,D.J. Augustin,https://www.basketball-reference.com/players/a...,12,PG,5-11,183,1987-11-10,us US,12,Texas,33,57,1129,2.1
4,2020-21,Milwaukee Bucks,MIL,bryanel01,Elijah Bryant,https://www.basketball-reference.com/players/b...,3,SG,6-5,210,1995-04-19,us US,R,"Elon University , BYU",25,1,32,0.0

In [169]:
champions.shape

(115, 18)

In [170]:
champions["season_id"] = (
    champions["season"]
    .map(season_map))

In [171]:
champion_team_player_df = champions[[
        "player_id",
        "season_id",
        "team_code"]].copy()

In [172]:
champion_team_player_df.drop_duplicates(inplace=True)

In [173]:
champion_team_player_df.shape

(115, 3)

In [174]:
champion_team_player_df.head()

   player_id  season_id team_code
0  adamsja01          2       MIL
1  antetgi01          2       MIL
2  antetth01          2       MIL
3  augusdj01          2       MIL
4  bryanel01          2       MIL

# DataBase

In [175]:
!pip install sqlalchemy --no-deps

Requirement already satisfied: sqlalchemy in f:\anaconda\envs\quera\lib\site-packages (2.0.51)

WARNING: Ignoring invalid distribution -umpy (f:\anaconda\envs\quera\lib\site-packages)
WARNING: Ignoring invalid distribution -umpy (f:\anaconda\envs\quera\lib\site-packages)

In [127]:
!pip install pymysql typing-extensions

Requirement already satisfied: pymysql in /Users/parsa/Desktop/projects/BOOTCAMP/PROJECT3/venv/lib/python3.13/site-packages (1.2.0)
Requirement already satisfied: typing-extensions in /Users/parsa/Desktop/projects/BOOTCAMP/PROJECT3/venv/lib/python3.13/site-packages (4.16.0)

[notice] A new release of pip is available: 25.0.1 -> 26.1.2
[notice] To update, run: pip install --upgrade pip

In [198]:
import sqlalchemy
import pymysql
from sqlalchemy import create_engine
from sqlalchemy import text
from urllib.parse import quote_plus
from dotenv import load_dotenv

In [201]:
from dotenv import dotenv_values

print(dotenv_values("../.env"))

OrderedDict([('DB_USERNAME', 'root'), ('PASSWORD', '6241423roy@'), ('HOST', 'localhost'), ('PORT', '3306'), ('DATABASE', 'basketball_db')])

In [203]:
with open("../.env", "rb") as f:
    print(f.read())

b'DB_USERNAME = \'root\'\r\nPASSWORD = \'6241423roy@\'\r\nHOST = \'localhost\'\r\nPORT = 3306\r\nDATABASE = "basketball_db"'

In [205]:
from dotenv import dotenv_values
print(dotenv_values("../.env"))

OrderedDict([('DB_USERNAME', 'root'), ('PASSWORD', '6241423roy@'), ('HOST', 'localhost'), ('PORT', '3306'), ('DATABASE', 'basketball_db')])

In [206]:
from dotenv import load_dotenv
import os

load_dotenv("../.env", override=True)

print(os.getenv("DB_USERNAME"))
print(os.getenv("PASSWORD"))
print(os.getenv("HOST"))
print(os.getenv("PORT"))
print(os.getenv("DATABASE"))

root
6241423roy@
localhost
3306
basketball_db

In [209]:
load_dotenv('../‌.env', override=True)

USERNAME = os.getenv('DB_USERNAME')
PASSWORD = os.getenv('PASSWORD')
HOST = os.getenv('HOST')
PORT = os.getenv('PORT')
DATABASE = os.getenv('DATABASE')

engine = create_engine(
    f"mysql+pymysql://{USERNAME}:{quote_plus(PASSWORD)}@{HOST}:{PORT}/{DATABASE}")

In [130]:
## in sqlalchemy all raw sql queries must be wrapped in text()

In [213]:
with engine.connect() as conn:
    print(conn.execute(text("SELECT DATABASE();")).fetchone())

('basketball_db',)

In [214]:
with engine.connect() as conn:
    result = conn.execute(text("SHOW TABLES"))

    for row in result:
        print(row[0])

championteamplayer
college
country
mvp_award
player
playercollege
playerposition
playerseasonstats
positions
season
team

### country

In [215]:
country_df.head()

   country_id country_code
0           1           ag
1           2           ao
2           3           ar
3           4           at
4           5           au

In [217]:
country_df.to_sql(
    name="country",
    con=engine,
    if_exists="append",
    index=False)

OperationalError: (pymysql.err.OperationalError) (1054, "Unknown column 'country_code' in 'field list'")
[SQL: INSERT INTO country (country_id, country_code) VALUES (%(country_id)s, %(country_code)s)]
[parameters: [{'country_id': 1, 'country_code': 'ag'}, {'country_id': 2, 'country_code': 'ao'}, {'country_id': 3, 'country_code': 'ar'}, {'country_id': 4, 'country_code': 'at'}, {'country_id': 5, 'country_code': 'au'}, {'country_id': 6, 'country_code': 'ba'}, {'country_id': 7, 'country_code': 'be'}, {'country_id': 8, 'country_code': 'bg'}  ... displaying 10 of 93 total bound parameter sets ...  {'country_id': 92, 'country_code': 'vi'}, {'country_id': 93, 'country_code': 'za'}]]
(Background on this error at: https://sqlalche.me/e/20/e3q8)

In [137]:
#test

In [138]:
with engine.connect() as conn:
    result = conn.execute(text("SELECT COUNT(*) FROM country"))
    print(result.scalar())

93

### college

In [139]:
college_df.head()

   college_id            college_name
0           1     1985in College Park
1           2       Acadia University
2           3               Air Force
3           4                 Alabama
4           5  Alabama A&M University

In [140]:
college_df.shape

(670, 2)

In [141]:
college_df.to_sql(name="college",
                    con=engine,
                    if_exists="append",
                    index=False)

670

### positions

In [151]:
position_df

   position_id position_code
0            1             C
1            2             F
2            3             G
3            4            PF
4            5            PG
5            6            SF
6            7            SG

In [152]:
position_df.to_sql(
    name="position",
    con=engine,
    if_exists="append",
    index=False)

7

### season

In [153]:
season_df

   season_id season_name
0          1     2019-20
1          2     2020-21
2          3     2021-22
3          4     2022-23
4          5     2023-24

In [154]:
season_df.to_sql(name="season",
                con=engine,
                if_exists="append",
                index=False)

5

### team

In [157]:
team_df.head()

  team_code
0       2TM
1       3TM
2       4TM
3       ATL
4       BOS

In [158]:
team_df.shape

(33, 1)

In [159]:
team_df.to_sql(name="team",
    con=engine,
    if_exists="append",
    index=False)

33

### player

In [160]:
player_df.head()

,player_id,full_name,birth_date,birth_place,height_cm,weight_kg,shoots,player_url,country_id
0,aubucch01,Chet Aubuchon,1916-05-18,"Gary,Indianaus",178,62.0,Right,https://www.basketball-reference.com/players/a...,86
1,willial06,Alondes Williams,1999-06-19,"Milwaukee ,Wisconsinus",193,95.0,Right,https://www.basketball-reference.com/players/w...,86
2,barnhle01,Leo Barnhorst,1924-05-11,"Indianapolis,Indianaus",193,86.0,Right,https://www.basketball-reference.com/players/b...,86
3,morriis01,Isaiah Morris,1969-04-02,"Richmond,Virginiaus",203,103.0,Right,https://www.basketball-reference.com/players/m...,86
4,jacksja01,Jaren Jackson,1967-10-27,"New Orleans,Louisianaus",193,86.0,Right,https://www.basketball-reference.com/players/j...,86

In [161]:
player_df.shape

(5416, 9)

In [162]:
player_df.dtypes

player_id                 str
full_name                 str
birth_date     datetime64[us]
birth_place               str
height_cm               int64
weight_kg             float64
shoots                    str
player_url                str
country_id              int64
dtype: object

In [165]:
player_df.to_sql(
    name="player",
    con=engine,
    if_exists="append",
    index=False)

5416

In [163]:
#test

In [166]:
with engine.connect() as conn:
    result = conn.execute(text("SELECT COUNT(*) FROM player"))
    print(result.scalar())

5416

### player_college

In [168]:
player_college_df.head()

   player_id  college_id
0  aubucch01         326
1  willial06         538
2  willial06         407
3  willial06         623
4  barnhle01         398

In [169]:
player_college_df.shape

(5751, 2)

In [172]:
player_college_df.to_sql(name="playercollege",
                            con=engine,
                            if_exists="append",
                            index=False)

DatabaseError: Execution failed on sql 'INSERT INTO playercollege (player_id, college_id) VALUES (:player_id, :college_id)': (pymysql.err.IntegrityError) (1062, "Duplicate entry 'aubucch01-326' for key 'playercollege.PRIMARY'")
[SQL: INSERT INTO playercollege (player_id, college_id) VALUES (%(player_id)s, %(college_id)s)]
[parameters: [{'player_id': 'aubucch01', 'college_id': 326}, {'player_id': 'willial06', 'college_id': 538}, {'player_id': 'willial06', 'college_id': 407}, {'player_id': 'willial06', 'college_id': 623}, {'player_id': 'barnhle01', 'college_id': 398}, {'player_id': 'morriis01', 'college_id': 20}, {'player_id': 'jacksja01', 'college_id': 180}, {'player_id': 'gillan01', 'college_id': 487}  ... displaying 10 of 5751 total bound parameter sets ...  {'player_id': 'allrela01', 'college_id': 607}, {'player_id': 'allrela01', 'college_id': 631}]]
(Background on this error at: https://sqlalche.me/e/20/gkpj)

### player_position

In [173]:
player_position_df.head()

   player_id  position_id
0  aubucch01            3
1  willial06            7
2  barnhle01            6
3  morriis01            6
4  jacksja01            7

In [174]:
player_position_df.shape

(7156, 2)

In [176]:
player_position_df.to_sql(name="playerposition",
                            con=engine,
                            if_exists="append",
                            index=False)

DatabaseError: Execution failed on sql 'INSERT INTO playerposition (player_id, position_id) VALUES (:player_id, :position_id)': (pymysql.err.IntegrityError) (1062, "Duplicate entry 'aubucch01-3' for key 'playerposition.PRIMARY'")
[SQL: INSERT INTO playerposition (player_id, position_id) VALUES (%(player_id)s, %(position_id)s)]
[parameters: [{'player_id': 'aubucch01', 'position_id': 3}, {'player_id': 'willial06', 'position_id': 7}, {'player_id': 'barnhle01', 'position_id': 6}, {'player_id': 'morriis01', 'position_id': 6}, {'player_id': 'jacksja01', 'position_id': 7}, {'player_id': 'santogu01', 'position_id': 4}, {'player_id': 'gillan01', 'position_id': 4}, {'player_id': 'rhodege01', 'position_id': 7}  ... displaying 10 of 7156 total bound parameter sets ...  {'player_id': 'holcora01', 'position_id': 6}, {'player_id': 'allrela01', 'position_id': 1}]]
(Background on this error at: https://sqlalche.me/e/20/gkpj)

### player_season_stats

In [191]:
player_season_stats_df.head()

,player_id,season_id,team_code,age,games,games_started,minutes,win_shares,ws_per_48,bpm,vorp
0,hardeja01,1,HOU,30,68,68,2483,13.1,0.254,9.6,7.3
1,lillada01,1,POR,29,66,66,2474,11.6,0.225,7.5,5.9
2,antetgi01,1,MIL,25,63,63,1917,11.1,0.279,11.5,6.6
3,davisan02,1,LAL,26,62,62,2131,11.1,0.250,8.0,5.4
4,goberru01,1,UTA,27,68,68,2333,10.7,0.221,3.6,3.3

In [177]:
player_season_stats_df.shape

(2785, 11)

In [178]:
player_season_stats_df.to_sql(name="playerseasonstats",
                                con=engine,
                                if_exists="append",
                                index=False)

2785

### mvp_award

In [197]:
mvp_award_df.head()

   player_id  season_id  mvp_rank  mvp_share
0  antetgi01          1       1.0      0.952
1  jamesle01          1       2.0      0.746
2  hardeja01          1       3.0      0.363
3  doncilu01          1       4.0      0.198
4  leonaka01          1       5.0      0.166

In [198]:
mvp_award_df['team_code'].value_counts()

KeyError: 'team_code'

In [199]:
mvp_award_df.shape

(61, 4)

In [200]:
mvp_award_df.to_sql(name="mvp_award",
                            con=engine,
                            if_exists="append",
                            index=False)

DatabaseError: Execution failed on sql 'INSERT INTO mvp_award (player_id, season_id, mvp_rank, mvp_share) VALUES (:player_id, :season_id, :mvp_rank, :mvp_share)': (pymysql.err.IntegrityError) (1062, "Duplicate entry 'antetgi01-1' for key 'mvp_award.PRIMARY'")
[SQL: INSERT INTO mvp_award (player_id, season_id, mvp_rank, mvp_share) VALUES (%(player_id)s, %(season_id)s, %(mvp_rank)s, %(mvp_share)s)]
[parameters: [{'player_id': 'antetgi01', 'season_id': 1, 'mvp_rank': 1.0, 'mvp_share': 0.952}, {'player_id': 'jamesle01', 'season_id': 1, 'mvp_rank': 2.0, 'mvp_share': 0.746}, {'player_id': 'hardeja01', 'season_id': 1, 'mvp_rank': 3.0, 'mvp_share': 0.363}, {'player_id': 'doncilu01', 'season_id': 1, 'mvp_rank': 4.0, 'mvp_share': 0.198}, {'player_id': 'leonaka01', 'season_id': 1, 'mvp_rank': 5.0, 'mvp_share': 0.166}, {'player_id': 'davisan02', 'season_id': 1, 'mvp_rank': 6.0, 'mvp_share': 0.081}, {'player_id': 'paulch01', 'season_id': 1, 'mvp_rank': 7.0, 'mvp_share': 0.026}, {'player_id': 'lillada01', 'season_id': 1, 'mvp_rank': 8.0, 'mvp_share': 0.023}  ... displaying 10 of 61 total bound parameter sets ...  {'player_id': 'sabondo01', 'season_id': 5, 'mvp_rank': 8.0, 'mvp_share': 0.003}, {'player_id': 'duranke01', 'season_id': 5, 'mvp_rank': 9.0, 'mvp_share': 0.001}]]
(Background on this error at: https://sqlalche.me/e/20/gkpj)

### champion_team_player

In [201]:
champion_team_player_df.head()

   player_id  season_id team_code
0  adamsja01          2       MIL
1  antetgi01          2       MIL
2  antetth01          2       MIL
3  augusdj01          2       MIL
4  bryanel01          2       MIL

In [202]:
champion_team_player_df.shape

(76, 3)

In [203]:
champion_team_player_df.to_sql(name="championteamplayer",
                                con=engine,
                                if_exists="append",
                                index=False)

76