### Imports

In [2]:
import pandas as pd
import re

## Players

In [5]:
load_dotenv('../.env')
USERNAME = os.getenv('DB_USERNAME')
PASSWORD = os.getenv('PASSWORD')
HOST = os.getenv('HOST')
PORT = os.getenv('PORT')
DATABASE = os.getenv('DATABASE')

NameError: name 'load_dotenv' is not defined

In [ ]:
players_raw.shape

(5416, 24)

In [ ]:
players_raw.columns

Index(['Unnamed: 0', 'player_id', 'full_name', 'birth_date', 'born', 'height',
       'weight', 'nationality', 'position', 'shoots', 'college', 'high_school',
       'career_length', 'link', 'G', 'PTS', 'AST', 'FG%', 'FT%', 'WS', 'TRB',
       'FG3%', 'eFG%', 'PER'],
      dtype='object')

In [ ]:
players_raw.head(20)

,Unnamed: 0,player_id,full_name,birth_date,born,height,weight,nationality,position,shoots,...,G,PTS,AST,FG%,FT%,WS,TRB,FG3%,eFG%,PER
0,0,aubucch01,Chet Aubuchon,"May 18,1916","Gary,Indianaus",178,62.0,us,Guard,Right,...,30.0,2.2,0.7,25.3,54.3,1.2,NaN,NaN,NaN,NaN
1,1,willial06,Alondes Williams,"June 19,1999","Milwaukee ,Wisconsinus",193,95.0,us,Shooting Guard,Right,...,13.0,4.2,1.0,55.6,88.9,0.2,2.1,31.6,63.9,15.1
2,2,barnhle01,Leo Barnhorst,"May 11,1924","Indianapolis,Indianaus",193,86.0,us,Small Forward,Right,...,344.0,9.4,3.2,36.8,66.5,13.3,5.4,NaN,NaN,14.2
3,3,morriis01,Isaiah Morris,"April 2,1969","Richmond,Virginiaus",203,103.0,us,Small Forward,Right,...,25.0,2.2,0.2,45.6,75.0,0.0,0.5,NaN,45.6,10.6
4,4,jacksja01,Jaren Jackson,"October 27,1967","New Orleans,Louisianaus",193,86.0,us,Shooting Guard,Right,...,431.0,5.5,1.2,39.1,76.4,11.5,1.8,35.3,46.9,10.1
5,5,santogu01,Gui Santos,"June 22,2002","Brasilia,Brazilbr",201,83.0,br,Power Forward,Right,...,147.0,6.4,1.7,49.0,73.7,5.2,3.3,34.7,57.8,13.5
6,6,gillan01,Anthony Gill,"October 17,1992","High Point,North Carolinaus",201,104.0,us,Power Forward,Right,...,285.0,3.8,0.7,54.5,74.9,5.8,1.9,31.2,58.5,12.5
7,7,rhodege01,Gene Rhodes,"September 2,1927","St. Louis,Missourius",185,77.0,us,Shooting Guard,Right,...,65.0,5.2,1.4,31.9,70.4,0.9,1.5,NaN,NaN,11.2
8,8,brownle02,Lewis Brown,"February 19,1955","Los Angeles,Californiaus",211,102.0,us,Center,Left,...,2.0,1.0,0.0,0.0,40.0,-0.1,1.0,NaN,0.0,-18.6
9,9,hicksph01,Phil Hicks,"January 31,1953","Chicago,Illinoisus",201,92.0,us,Small Forward,Right,...,57.0,2.3,0.6,44.7,77.8,0.5,1.6,NaN,NaN,11.0
10,10,harrija01,Jalen Harris,"August 14,1998","Dallas,Texasus",196,88.0,us,Shooting Guard,Right,...,13.0,7.4,1.3,50.0,77.8,0.3,1.4,47.2,61.8,15.2
11,11,dykerge01,Gene Dyker,"February 17,1930","Chicago,Illinoisus",198,102.0,us,Forward,Right,...,11.0,1.5,0.5,23.1,50.0,-0.3,1.5,NaN,NaN,0.4
12,12,conlege01,Gene Conley,"November 10,1930","Muskogee,Oklahomaus",203,102.0,us,Power Forward,Right,...,351.0,5.9,0.6,37.1,65.7,5.1,6.3,NaN,NaN,10.2
13,13,longwi01,Willie Long,"March 1,1950","Fort Wayne,Indianaus",203,102.0,us,Power Forward and Small Forward,Right,...,213.0,11.4,1.0,42.1,77.4,6.9,6.0,0.0,42.1,13.1
14,14,hillsi01,Simmie Hill,"November 14,1946","Midland,Pennsylvaniaus",201,105.0,us,Small Forward,Right,...,252.0,9.7,1.3,43.2,76.3,6.9,5.3,29.3,44.0,11.4
15,15,pietrmi01,Mickaël Piétrus,"February 7,1982","Les Abymes,Guadeloupegp",198,97.0,gp,"Small Forward, Shooting Guard, and Point Guard",Right,...,557.0,8.3,0.8,42.5,66.5,19.7,3.1,35.5,51.4,11.6
16,16,knighne01,Negele Knight,"March 6,1967","Detroit,Michiganus",185,79.0,us,Point Guard,Right,...,276.0,6.2,2.8,43.6,73.0,4.2,1.3,26.3,44.4,11.3
17,17,willidu01,Duck Williams,"August 2,1956","Demopolis,Alabamaus",188,81.0,us,Point Guard,Right,...,77.0,6.6,2.4,44.7,70.0,-0.3,1.4,0.0,44.7,8.6
18,18,traorno01,Nolan Traoré,"May 28,2006","Créteil,Francefr",190,83.0,fr,Point Guard,Right,...,56.0,8.9,3.8,38.0,78.7,-1.6,1.8,31.8,44.4,7.9
19,19,alexavi01,Victor Alexander,"August 31,1969","Detroit,Michiganus",206,120.0,us,Center,Right,...,286.0,8.9,0.9,51.8,63.4,8.8,4.8,28.6,52.2,13.7

In [ ]:
players_raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5416 entries, 0 to 5415
Data columns (total 24 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Unnamed: 0     5416 non-null   int64
 1   player_id      5416 non-null   object
 2   full_name      5416 non-null   object
 3   birth_date     5309 non-null   object
 4   born           5412 non-null   object
 5   height         5416 non-null   int64
 6   weight         5411 non-null   float64
 7   nationality    5416 non-null   object
 8   position       5416 non-null   object
 9   shoots         5416 non-null   object
 10  college        5015 non-null   object
 11  high_school    4867 non-null   object
 12  career_length  4686 non-null   object
 13  link           5416 non-null   object
 14  G              5416 non-null   float64
 15  PTS            5416 non-null   float64
 16  AST            5416 non-null   float64
 17  FG%            5381 non-null   float64
 18  FT%            5164 non-null   float64
 19  WS             5415 non-null   float64
 20  TRB            5124 non-null   float64
 21  FG3%           3751 non-null   float64
 22  eFG%           4259 non-null   float64
 23  PER            5068 non-null   float64
dtypes: float64(11), int64(2), object(11)
memory usage: 1015.6+ KB

In [ ]:
len(players_raw['position'].unique())

44

In [ ]:
players_raw['position'].unique()

array(['Guard', 'Shooting Guard', 'Small Forward', 'Power Forward',
       'Center', 'Forward', 'Power Forward and Small Forward',
       'Small Forward, Shooting Guard, and Point Guard', 'Point Guard',
       'Small Forward and Power Forward',
       'Point Guard and Shooting Guard', 'Forward/Center',
       'Center and Power Forward', 'Shooting Guard and Small Forward',
       'Forward/Guard', 'Power Forward and Center',
       'Shooting Guard and Point Guard',
       'Small Forward and Shooting Guard',
       'Power Forward, Small Forward, and Center', 'Center/Forward',
       'Shooting Guard, Point Guard, and Small Forward',
       'Small Forward, Power Forward, and Shooting Guard',
       'Guard/Forward', 'Power Forward, Center, and Small Forward',
       'Center, Power Forward, and Small Forward',
       'Shooting Guard, Small Forward, and Point Guard',
       'Point Guard and Small Forward',
       'Small Forward, Shooting Guard, and Power Forward',
       'Small Forward and Point Guard', 'Small Forward and Center',
       'Power Forward and Shooting Guard',
       'Small Forward, Power Forward, and Center',
       'Power Forward, Small Forward, and Shooting Guard',
       'Power Forward, Shooting Guard, and Small Forward',
       'Shooting Guard, Small Forward, and Power Forward',
       'Power Forward, Center, Forward, and Small Forward',
       'Power Forward, Small Forward, Point Guard, and Shooting Guard',
       'Point Guard, Shooting Guard, Power Forward, and Small Forward',
       'Small Forward, Center, and Power Forward',
       'Point Guard, Shooting Guard, and Power Forward',
       'Point Guard, Small Forward, and Shooting Guard',
       'Small Forward, Power Forward, Point Guard, Center, and Shooting Guard',
       'Shooting Guard and Power Forward', 'Center and Small Forward'],
      dtype=object)

In [ ]:
## position column needs Standardization

In [ ]:
players_raw['shoots'].value_counts()

shoots
Right        5035
Left          379
LeftRight       1
RightLeft       1
Name: count, dtype: int64

In [ ]:
## shoots needs standardization
## college has sevral values and I should split it

In [ ]:
players_raw['nationality'].value_counts()

nationality
us    4781
ca      60
fr      49
au      35
de      30
      ...
no       1
hu       1
uy       1
ir       1
bg       1
Name: count, Length: 93, dtype: int64

In [ ]:
players_raw['nationality'].unique()

array(['us', 'br', 'gp', 'fr', 'de', 'it', 'ru', 'lv', 'gh', 'ar', 'pl',
       'es', 'gb', 'sn', 'ng', 'gf', 'rs', 'mx', 'hr', 'jp', 'jm', 'il',
       'ch', 'lt', 'gr', 'nl', 'ua', 'ss', 'pa', 'do', 'ca', 'ga', 'cm',
       'au', 'bs', 'si', 'cz', 'ee', 'ht', 'tr', 'cn', 'cd', 'ml', 'gn',
       'mk', 'sd', 'bg', 'ag', 'ir', 'no', 'tz', 'kr', 'cg', 'ie', 'ba',
       'za', 'cu', 'me', 'lb', 'vg', 'uz', 'is', 'pt', 'nz', 'tw', 'se',
       'tn', 'eg', 'dk', 'vc', 'pr', 'hu', 'uy', 'be', 'ge', 'sk', 'gy',
       'ro', 'vi', 'ni', 'mq', 'cy', 'cv', 'fi', 'dm', 'lc', 'co', 'at',
       'lu', 'ma', 've', 'ao', 'tt'], dtype=object)

### cleaning and standardization Players raw data

In [ ]:
players = players_raw.drop(columns=["Unnamed: 0"])

In [ ]:
## converting birthdate format to datetime

In [ ]:
players["birth_date"] = pd.to_datetime(
    players["birth_date"],
    format="%B %d,%Y",
    errors="coerce"
)

In [ ]:
## position column standardization

In [ ]:
position_map = {
    "Point Guard": "PG",
    "Shooting Guard": "SG",
    "Small Forward": "SF",
    "Power Forward": "PF",
    "Center": "C",
    "Guard": "G",
    "Forward": "F"
}

In [ ]:
def normalize_positions(pos):

    if pd.isna(pos):
        return None

    parts = re.split(r",| and |/", pos)

    positions = []

    for part in parts:
        part = part.strip()

        if part in position_map:
            positions.append(position_map[part])

    return sorted(set(positions))

In [ ]:
players["position"] = players["position"].apply(normalize_positions)

In [ ]:
## shoots column standardization

In [ ]:
shoot_map = {"Right": "Right",
             "Left": "Left",
             "LeftRight": "Both",
             "RightLeft": "Both"}

players["shoots"] = players["shoots"].replace(shoot_map)

In [ ]:
players.head()

,player_id,full_name,birth_date,born,height,weight,nationality,position,shoots,college,...,G,PTS,AST,FG%,FT%,WS,TRB,FG3%,eFG%,PER
0,aubucch01,Chet Aubuchon,1916-05-18,"Gary,Indianaus",178,62.0,us,[G],Right,Michigan State,...,30.0,2.2,0.7,25.3,54.3,1.2,NaN,NaN,NaN,NaN
1,willial06,Alondes Williams,1999-06-19,"Milwaukee ,Wisconsinus",193,95.0,us,[SG],Right,"Colleges:Triton College,Oklahoma,Wake Forest",...,13.0,4.2,1.0,55.6,88.9,0.2,2.1,31.6,63.9,15.1
2,barnhle01,Leo Barnhorst,1924-05-11,"Indianapolis,Indianaus",193,86.0,us,[SF],Right,Notre Dame,...,344.0,9.4,3.2,36.8,66.5,13.3,5.4,NaN,NaN,14.2
3,morriis01,Isaiah Morris,1969-04-02,"Richmond,Virginiaus",203,103.0,us,[SF],Right,Arkansas,...,25.0,2.2,0.2,45.6,75.0,0.0,0.5,NaN,45.6,10.6
4,jacksja01,Jaren Jackson,1967-10-27,"New Orleans,Louisianaus",193,86.0,us,[SG],Right,Georgetown,...,431.0,5.5,1.2,39.1,76.4,11.5,1.8,35.3,46.9,10.1

In [ ]:
players.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5416 entries, 0 to 5415
Data columns (total 23 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   player_id      5416 non-null   object
 1   full_name      5416 non-null   object
 2   birth_date     5305 non-null   datetime64[ns]
 3   born           5412 non-null   object
 4   height         5416 non-null   int64
 5   weight         5411 non-null   float64
 6   nationality    5416 non-null   object
 7   position       5416 non-null   object
 8   shoots         5416 non-null   object
 9   college        5015 non-null   object
 10  high_school    4867 non-null   object
 11  career_length  4686 non-null   object
 12  link           5416 non-null   object
 13  G              5416 non-null   float64
 14  PTS            5416 non-null   float64
 15  AST            5416 non-null   float64
 16  FG%            5381 non-null   float64
 17  FT%            5164 non-null   float64
 18  WS             5415 non-null   float64
 19  TRB            5124 non-null   float64
 20  FG3%           3751 non-null   float64
 21  eFG%           4259 non-null   float64
 22  PER            5068 non-null   float64
dtypes: datetime64[ns](1), float64(11), int64(1), object(10)
memory usage: 973.3+ KB

## Advanced_stats_all_rows

In [ ]:
adv_rows_raw = pd.read_csv('raw_data/advanced_stats_all_seasons.csv')

In [ ]:
adv_rows_raw.shape

(2785, 14)

In [ ]:
adv_rows_raw.head(10)

,season,player_id,player_name,player_url,age,team,position,games,games_started,minutes,win_shares,ws_per_48,bpm,vorp
0,2019-20,hardeja01,James Harden,https://www.basketball-reference.com/players/h...,30,HOU,SG,68,68,2483,13.1,0.254,9.6,7.3
1,2019-20,lillada01,Damian Lillard,https://www.basketball-reference.com/players/l...,29,POR,PG,66,66,2474,11.6,0.225,7.5,5.9
2,2019-20,antetgi01,Giannis Antetokounmpo,https://www.basketball-reference.com/players/a...,25,MIL,PF,63,63,1917,11.1,0.279,11.5,6.6
3,2019-20,davisan02,Anthony Davis,https://www.basketball-reference.com/players/d...,26,LAL,PF,62,62,2131,11.1,0.250,8.0,5.4
4,2019-20,goberru01,Rudy Gobert,https://www.basketball-reference.com/players/g...,27,UTA,C,68,68,2333,10.7,0.221,3.6,3.3
5,2019-20,jamesle01,LeBron James,https://www.basketball-reference.com/players/j...,35,LAL,PG,67,67,2316,9.8,0.204,8.4,6.1
6,2019-20,jokicni01,Nikola Jokić,https://www.basketball-reference.com/players/j...,24,DEN,C,73,73,2336,9.8,0.202,7.4,5.5
7,2019-20,butleji01,Jimmy Butler,https://www.basketball-reference.com/players/b...,30,MIA,SF,58,58,1959,9.0,0.221,5.4,3.7
8,2019-20,paulch01,Chris Paul,https://www.basketball-reference.com/players/p...,34,OKC,PG,70,70,2208,8.9,0.193,4.4,3.5
9,2019-20,doncilu01,Luka Dončić,https://www.basketball-reference.com/players/d...,20,DAL,PG,61,61,2047,8.8,0.207,8.4,5.4

In [ ]:
adv_rows_raw.columns

Index(['season', 'player_id', 'player_name', 'player_url', 'age', 'team',
       'position', 'games', 'games_started', 'minutes', 'win_shares',
       'ws_per_48', 'bpm', 'vorp'],
      dtype='object')

In [ ]:
adv_rows_raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2785 entries, 0 to 2784
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   season         2785 non-null   object
 1   player_id      2785 non-null   object
 2   player_name    2785 non-null   object
 3   player_url     2785 non-null   object
 4   age            2785 non-null   int64
 5   team           2785 non-null   object
 6   position       2785 non-null   object
 7   games          2785 non-null   int64
 8   games_started  2785 non-null   int64
 9   minutes        2785 non-null   int64
 10  win_shares     2785 non-null   float64
 11  ws_per_48      2785 non-null   float64
 12  bpm            2785 non-null   float64
 13  vorp           2785 non-null   float64
dtypes: float64(4), int64(4), object(6)
memory usage: 304.7+ KB

In [ ]:
adv_rows_raw['position'].unique()

array(['SG', 'PG', 'PF', 'C', 'SF'], dtype=object)

In [ ]:
adv_rows_raw['position'].value_counts()

position
SG    668
PF    546
SF    540
C     527
PG    504
Name: count, dtype: int64

In [ ]:
adv_rows_raw['season'].unique()

array(['2019-20', '2020-21', '2021-22', '2022-23', '2023-24'],
      dtype=object)

## Champion players all seasons

In [ ]:
champ_seasons_raw = pd.read_csv('raw_data/champion_players_all_seasons.csv')

In [ ]:
champ_seasons_raw.shape

(76, 18)

In [ ]:
champ_seasons_raw.head()

,season,champion_team,team_code,player_id,player_name,player_url,number,position,height,weight,birth_date,birth_place,experience,college,age,games,minutes,win_shares
0,2020-21,Milwaukee Bucks,MIL,adamsja01,Jaylen Adams,https://www.basketball-reference.com/players/a...,6,PG,6-0,225,1996-05-04,us US,2,St. Bonaventure,24,7,18,-0.1
1,2020-21,Milwaukee Bucks,MIL,antetgi01,Giannis Antetokounmpo,https://www.basketball-reference.com/players/a...,34,PF,6-11,243,1994-12-06,gr GR,7,NaN,26,61,2013,10.2
2,2020-21,Milwaukee Bucks,MIL,antetth01,Thanasis Antetokounmpo,https://www.basketball-reference.com/players/a...,43,SF,6-7,219,1992-07-18,gr GR,2,NaN,28,57,551,0.7
3,2020-21,Milwaukee Bucks,MIL,augusdj01,D.J. Augustin,https://www.basketball-reference.com/players/a...,12,PG,5-11,183,1987-11-10,us US,12,Texas,33,57,1129,2.1
4,2020-21,Milwaukee Bucks,MIL,bryanel01,Elijah Bryant,https://www.basketball-reference.com/players/b...,3,SG,6-5,210,1995-04-19,us US,R,"Elon University , BYU",25,1,32,0.0

In [ ]:
champ_seasons_raw.columns

Index(['season', 'champion_team', 'team_code', 'player_id', 'player_name',
       'player_url', 'number', 'position', 'height', 'weight', 'birth_date',
       'birth_place', 'experience', 'college', 'age', 'games', 'minutes',
       'win_shares'],
      dtype='object')

In [ ]:
champ_seasons_raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 76 entries, 0 to 75
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   season         76 non-null     object
 1   champion_team  76 non-null     object
 2   team_code      76 non-null     object
 3   player_id      76 non-null     object
 4   player_name    76 non-null     object
 5   player_url     76 non-null     object
 6   number         76 non-null     int64
 7   position       76 non-null     object
 8   height         76 non-null     object
 9   weight         76 non-null     int64
 10  birth_date     76 non-null     object
 11  birth_place    76 non-null     object
 12  experience     76 non-null     object
 13  college        67 non-null     object
 14  age            76 non-null     int64
 15  games          76 non-null     int64
 16  minutes        76 non-null     int64
 17  win_shares     76 non-null     float64
dtypes: float64(1), int64(5), object(12)
memory usage: 10.8+ KB

In [ ]:
champ_seasons_raw['champion_team'].value_counts()

champion_team
Milwaukee Bucks          22
Boston Celtics           19
Denver Nuggets           18
Golden State Warriors    17
Name: count, dtype: int64

In [ ]:
champions = champ_seasons_raw.copy()

In [ ]:
champions.shape

(76, 18)

In [ ]:
champions.head()

,season,champion_team,team_code,player_id,player_name,player_url,number,position,height,weight,birth_date,birth_place,experience,college,age,games,minutes,win_shares
0,2020-21,Milwaukee Bucks,MIL,adamsja01,Jaylen Adams,https://www.basketball-reference.com/players/a...,6,PG,183,102.1,1996-05-04,us US,2,St. Bonaventure,24,7,18,-0.1
1,2020-21,Milwaukee Bucks,MIL,antetgi01,Giannis Antetokounmpo,https://www.basketball-reference.com/players/a...,34,PF,211,110.2,1994-12-06,gr GR,7,NaN,26,61,2013,10.2
2,2020-21,Milwaukee Bucks,MIL,antetth01,Thanasis Antetokounmpo,https://www.basketball-reference.com/players/a...,43,SF,201,99.3,1992-07-18,gr GR,2,NaN,28,57,551,0.7
3,2020-21,Milwaukee Bucks,MIL,augusdj01,D.J. Augustin,https://www.basketball-reference.com/players/a...,12,PG,180,83.0,1987-11-10,us US,12,Texas,33,57,1129,2.1
4,2020-21,Milwaukee Bucks,MIL,bryanel01,Elijah Bryant,https://www.basketball-reference.com/players/b...,3,SG,196,95.3,1995-04-19,us US,R,"Elon University , BYU",25,1,32,0.0

## MVP

In [ ]:
mvp_all_seasons_raw = pd.read_csv('raw_data/mvp_all_seasons.csv')

In [ ]:
mvp_all_seasons_raw.shape

(61, 7)

In [ ]:
mvp_all_seasons_raw.head()

,season,mvp_rank,player_id,player_name,player_url,team,mvp_share
0,2019-20,1.0,antetgi01,Giannis Antetokounmpo,/players/a/antetgi01.html,MIL,0.952
1,2019-20,2.0,jamesle01,LeBron James,/players/j/jamesle01.html,LAL,0.746
2,2019-20,3.0,hardeja01,James Harden,/players/h/hardeja01.html,HOU,0.363
3,2019-20,4.0,doncilu01,Luka Dončić,/players/d/doncilu01.html,DAL,0.198
4,2019-20,5.0,leonaka01,Kawhi Leonard,/players/l/leonaka01.html,LAC,0.166

In [ ]:
mvp_all_seasons_raw['season'].value_counts()

season
2020-21    15
2022-23    13
2019-20    12
2021-22    12
2023-24     9
Name: count, dtype: int64

In [ ]:
mvp_all_seasons_raw['team'].value_counts()

team
MIL    5
DAL    5
DEN    5
BOS    4
PHO    4
LAL    4
PHI    4
SAC    3
NYK    3
GSW    3
OKC    3
MIA    2
POR    2
LAC    2
TOT    2
MEM    2
TOR    1
UTA    1
WAS    1
CHI    1
BRK    1
CLE    1
HOU    1
MIN    1
Name: count, dtype: int64

In [ ]:
mvp_all_seasons_raw['player_name'].value_counts()

player_name
Giannis Antetokounmpo      5
Luka Dončić                5
Nikola Jokić               5
Jayson Tatum               4
Chris Paul                 3
LeBron James               3
Stephen Curry              3
Joel Embiid                3
Kevin Durant               2
Shai Gilgeous-Alexander    2
Domantas Sabonis           2
Jimmy Butler               2
Ja Morant                  2
Damian Lillard             2
Jalen Brunson              2
Kawhi Leonard              2
James Harden               2
De'Aaron Fox               1
Donovan Mitchell           1
DeMar DeRozan              1
Julius Randle              1
Devin Booker               1
Ben Simmons                1
Russell Westbrook          1
Rudy Gobert                1
Derrick Rose               1
Pascal Siakam              1
Anthony Davis              1
Anthony Edwards            1
Name: count, dtype: int64

In [ ]:
len(mvp_all_seasons_raw['player_name'].unique())

29

In [ ]:
mvp_all_seasons_raw['team'].value_counts()

team
MIL    5
DAL    5
DEN    5
BOS    4
PHO    4
LAL    4
PHI    4
SAC    3
NYK    3
GSW    3
OKC    3
MIA    2
POR    2
LAC    2
TOT    2
MEM    2
TOR    1
UTA    1
WAS    1
CHI    1
BRK    1
CLE    1
HOU    1
MIN    1
Name: count, dtype: int64

## Creating DataFrames

### Players DataFrame

In [ ]:
players.head()

,player_id,full_name,birth_date,born,height,weight,nationality,position,shoots,college,...,G,PTS,AST,FG%,FT%,WS,TRB,FG3%,eFG%,PER
0,aubucch01,Chet Aubuchon,1916-05-18,"Gary,Indianaus",178,62.0,us,[G],Right,Michigan State,...,30.0,2.2,0.7,25.3,54.3,1.2,NaN,NaN,NaN,NaN
1,willial06,Alondes Williams,1999-06-19,"Milwaukee ,Wisconsinus",193,95.0,us,[SG],Right,"Colleges:Triton College,Oklahoma,Wake Forest",...,13.0,4.2,1.0,55.6,88.9,0.2,2.1,31.6,63.9,15.1
2,barnhle01,Leo Barnhorst,1924-05-11,"Indianapolis,Indianaus",193,86.0,us,[SF],Right,Notre Dame,...,344.0,9.4,3.2,36.8,66.5,13.3,5.4,NaN,NaN,14.2
3,morriis01,Isaiah Morris,1969-04-02,"Richmond,Virginiaus",203,103.0,us,[SF],Right,Arkansas,...,25.0,2.2,0.2,45.6,75.0,0.0,0.5,NaN,45.6,10.6
4,jacksja01,Jaren Jackson,1967-10-27,"New Orleans,Louisianaus",193,86.0,us,[SG],Right,Georgetown,...,431.0,5.5,1.2,39.1,76.4,11.5,1.8,35.3,46.9,10.1

In [ ]:
player_df = players[
    ["player_id",
     "full_name",
     "birth_date",
      "born",
      "height",
      "weight",
      "shoots",
      "link"]].copy()

player_df.rename(columns={
    "born": "birth_place",
    "height": "height_cm",
    "weight": "weight_kg",
    "link": "player_url"
}, inplace=True)

In [ ]:
player_df.head()

,player_id,full_name,birth_date,birth_place,height_cm,weight_kg,shoots,player_url
0,aubucch01,Chet Aubuchon,1916-05-18,"Gary,Indianaus",178,62.0,Right,https://www.basketball-reference.com/players/a...
1,willial06,Alondes Williams,1999-06-19,"Milwaukee ,Wisconsinus",193,95.0,Right,https://www.basketball-reference.com/players/w...
2,barnhle01,Leo Barnhorst,1924-05-11,"Indianapolis,Indianaus",193,86.0,Right,https://www.basketball-reference.com/players/b...
3,morriis01,Isaiah Morris,1969-04-02,"Richmond,Virginiaus",203,103.0,Right,https://www.basketball-reference.com/players/m...
4,jacksja01,Jaren Jackson,1967-10-27,"New Orleans,Louisianaus",193,86.0,Right,https://www.basketball-reference.com/players/j...

### Country DataFrame

In [ ]:
len(players['nationality'].unique())

93

In [ ]:
country_df = (
    players[["nationality"]]
    .dropna()
    .drop_duplicates()
    .sort_values("nationality")
    .reset_index(drop=True))

In [ ]:
country_df.insert(0, "country_id", range(1, len(country_df) + 1))

In [ ]:
country_df.rename(columns={
    "nationality": "country_name"}, inplace=True)

In [ ]:
country_df.head()

   country_id country_name
0           1           ag
1           2           ao
2           3           ar
3           4           at
4           5           au

In [ ]:
country_df.shape

(93, 2)

In [ ]:
## adding country_id as a foreign key to players_df

In [ ]:
country_map = dict(zip(
        country_df["country_name"],
        country_df["country_id"]))

In [ ]:
player_df["country_id"] = players["nationality"].map(country_map)

In [ ]:
player_df.head()

,player_id,full_name,birth_date,birth_place,height_cm,weight_kg,shoots,player_url,country_id
0,aubucch01,Chet Aubuchon,1916-05-18,"Gary,Indianaus",178,62.0,Right,https://www.basketball-reference.com/players/a...,86
1,willial06,Alondes Williams,1999-06-19,"Milwaukee ,Wisconsinus",193,95.0,Right,https://www.basketball-reference.com/players/w...,86
2,barnhle01,Leo Barnhorst,1924-05-11,"Indianapolis,Indianaus",193,86.0,Right,https://www.basketball-reference.com/players/b...,86
3,morriis01,Isaiah Morris,1969-04-02,"Richmond,Virginiaus",203,103.0,Right,https://www.basketball-reference.com/players/m...,86
4,jacksja01,Jaren Jackson,1967-10-27,"New Orleans,Louisianaus",193,86.0,Right,https://www.basketball-reference.com/players/j...,86

### college DataFrame

In [ ]:
def parse_colleges(college):
    if pd.isna(college):
        return []

    # rmeving college 
    college = college.replace("Colleges:", "")

    
    colleges = college.split(",")

    # removing extra soaces
    colleges = [c.strip() for c in colleges]

    # removing empty strings
    colleges = [c for c in colleges if c]

    return colleges

In [ ]:
all_colleges = []

for colleges in players["college"]:
    all_colleges.extend(parse_colleges(colleges))

In [ ]:
college_df = pd.DataFrame({
    "college_name": sorted(set(all_colleges))})

In [ ]:
college_df.insert(
    0,
    "college_id",
    range(1, len(college_df)+1))

In [ ]:
college_df.head()

   college_id            college_name
0           1     1985in College Park
1           2       Acadia University
2           3               Air Force
3           4                 Alabama
4           5  Alabama A&M University

In [ ]:
college_df.shape

(670, 2)

### player_college DataFrame

In [ ]:
# mapping college to each player

In [ ]:
college_map = dict(
    zip(
        college_df["college_name"],
        college_df["college_id"]))

In [ ]:
player_college_rows = []

for _, row in players.iterrows():

    colleges = parse_colleges(row["college"])

    for college in colleges:

        player_college_rows.append({
            "player_id": row["player_id"],
            "college_id": college_map[college]})

In [ ]:
player_college_df = pd.DataFrame(player_college_rows)

In [ ]:
player_college_df.drop_duplicates(inplace=True)

In [ ]:
player_college_df.head()

   player_id  college_id
0  aubucch01         326
1  willial06         538
2  willial06         407
3  willial06         623
4  barnhle01         398

In [ ]:
player_college_df.shape

(5751, 2)

### position DataFrame

In [ ]:
all_positions = []

for positions in players["position"]:
    if positions:
        all_positions.extend(positions)

In [ ]:
position_df = pd.DataFrame({
    "position_name": sorted(set(all_positions))})

In [ ]:
position_df.insert(0,
            "position_id",
            range(1, len(position_df) + 1))

In [ ]:
position_df.head()

   position_id position_name
0            1             C
1            2             F
2            3             G
3            4            PF
4            5            PG

In [ ]:
position_df.shape

(7, 2)

### player_position DataFrame

In [ ]:
position_map = dict(
    zip(
        position_df["position_name"],
        position_df["position_id"]
    )
)

In [ ]:
player_position_rows = []

for _, row in players.iterrows():

    positions = row["position"]

    if not positions:
        continue

    for position in positions:

        player_position_rows.append({
            "player_id": row["player_id"],
            "position_id": position_map[position]})

In [ ]:
player_position_df = pd.DataFrame(player_position_rows)

In [ ]:
player_position_df.drop_duplicates(inplace=True)

In [ ]:
player_position_df.head()

   player_id  position_id
0  aubucch01            3
1  willial06            7
2  barnhle01            6
3  morriis01            6
4  jacksja01            7

In [ ]:
player_position_df.shape

(7156, 2)

### season DataFrame

In [ ]:
season_df = (
    adv_rows_raw[["season"]]
    .drop_duplicates()
    .sort_values("season")
    .reset_index(drop=True))

In [ ]:
season_df.insert(
    0,
    "season_id",
    range(1, len(season_df)+1))

In [ ]:
season_df.rename(columns={
    "season": "season_name"}, inplace=True)

In [ ]:
season_df.head()

   season_id season_name
0          1     2019-20
1          2     2020-21
2          3     2021-22
3          4     2022-23
4          5     2023-24

### player_season_stats DataFrame

In [ ]:
season_map = dict(
    zip(
        season_df["season_name"],
        season_df["season_id"]))

In [ ]:
player_season_stats_df = adv_rows_raw[[
        "player_id",
        "team",
        "age",
        "games",
        "games_started",
        "minutes",
        "win_shares",
        "ws_per_48",
        "bpm",
        "vorp"
    ]
].copy()

In [ ]:
player_season_stats_df["season_id"] = (adv_rows_raw["season"].map(season_map))

In [ ]:
player_season_stats_df = player_season_stats_df[[
        "player_id",
        "season_id",
        "team",
        "age",
        "games",
        "games_started",
        "minutes",
        "win_shares",
        "ws_per_48",
        "bpm",
        "vorp"]]

In [ ]:
player_season_stats_df.rename(columns={
    "team": "team_code"
}, inplace=True)

In [ ]:
player_season_stats_df.head()

,player_id,season_id,team_code,age,games,games_started,minutes,win_shares,ws_per_48,bpm,vorp
0,hardeja01,1,HOU,30,68,68,2483,13.1,0.254,9.6,7.3
1,lillada01,1,POR,29,66,66,2474,11.6,0.225,7.5,5.9
2,antetgi01,1,MIL,25,63,63,1917,11.1,0.279,11.5,6.6
3,davisan02,1,LAL,26,62,62,2131,11.1,0.250,8.0,5.4
4,goberru01,1,UTA,27,68,68,2333,10.7,0.221,3.6,3.3

In [ ]:
player_season_stats_df.shape

(2785, 11)

### team DataFrame

In [ ]:
adv_rows_raw.head()

,season,player_id,player_name,player_url,age,team,position,games,games_started,minutes,win_shares,ws_per_48,bpm,vorp
0,2019-20,hardeja01,James Harden,https://www.basketball-reference.com/players/h...,30,HOU,SG,68,68,2483,13.1,0.254,9.6,7.3
1,2019-20,lillada01,Damian Lillard,https://www.basketball-reference.com/players/l...,29,POR,PG,66,66,2474,11.6,0.225,7.5,5.9
2,2019-20,antetgi01,Giannis Antetokounmpo,https://www.basketball-reference.com/players/a...,25,MIL,PF,63,63,1917,11.1,0.279,11.5,6.6
3,2019-20,davisan02,Anthony Davis,https://www.basketball-reference.com/players/d...,26,LAL,PF,62,62,2131,11.1,0.250,8.0,5.4
4,2019-20,goberru01,Rudy Gobert,https://www.basketball-reference.com/players/g...,27,UTA,C,68,68,2333,10.7,0.221,3.6,3.3

In [ ]:
adv_rows_raw['team'].unique()

array(['HOU', 'POR', 'MIL', 'LAL', 'UTA', 'DEN', 'MIA', 'OKC', 'DAL',
       'LAC', 'BRK', 'PHO', 'TOR', 'IND', 'SAS', 'MEM', 'PHI', 'BOS',
       'NYK', 'ORL', 'ATL', 'SAC', 'WAS', 'NOP', 'MIN', 'DET', '2TM',
       'CHI', 'CLE', 'CHO', 'GSW', '3TM', '4TM'], dtype=object)

In [ ]:
len(adv_rows_raw['team'].unique())

33

In [ ]:
champ_seasons_raw['team_code'].unique()

array(['MIL', 'GSW', 'DEN', 'BOS'], dtype=object)

In [ ]:
team_df = (adv_rows_raw[["team"]]
            .drop_duplicates()
            .rename(columns={"team": "team_code"})
            .sort_values("team_code")
            .reset_index(drop=True))

In [ ]:
team_df

   team_code
0        2TM
1        3TM
2        4TM
3        ATL
4        BOS
5        BRK
6        CHI
7        CHO
8        CLE
9        DAL
10       DEN
11       DET
12       GSW
13       HOU
14       IND
15       LAC
16       LAL
17       MEM
18       MIA
19       MIL
20       MIN
21       NOP
22       NYK
23       OKC
24       ORL
25       PHI
26       PHO
27       POR
28       SAC
29       SAS
30       TOR
31       UTA
32       WAS

In [ ]:
team_df

   team_code
0        2TM
1        3TM
2        4TM
3        ATL
4        BOS
5        BRK
6        CHI
7        CHO
8        CLE
9        DAL
10       DEN
11       DET
12       GSW
13       HOU
14       IND
15       LAC
16       LAL
17       MEM
18       MIA
19       MIL
20       MIN
21       NOP
22       NYK
23       OKC
24       ORL
25       PHI
26       PHO
27       POR
28       SAC
29       SAS
30       TOR
31       UTA
32       WAS

### mvp_awards DataFrame

In [ ]:
mvp_all_seasons_raw.head()

,season,mvp_rank,player_id,player_name,player_url,team,mvp_share
0,2019-20,1.0,antetgi01,Giannis Antetokounmpo,/players/a/antetgi01.html,MIL,0.952
1,2019-20,2.0,jamesle01,LeBron James,/players/j/jamesle01.html,LAL,0.746
2,2019-20,3.0,hardeja01,James Harden,/players/h/hardeja01.html,HOU,0.363
3,2019-20,4.0,doncilu01,Luka Dončić,/players/d/doncilu01.html,DAL,0.198
4,2019-20,5.0,leonaka01,Kawhi Leonard,/players/l/leonaka01.html,LAC,0.166

In [ ]:
mvp_all_seasons_raw.shape

(61, 7)

In [ ]:
mvp_awards = mvp_all_seasons_raw.copy()

In [ ]:
mvp_awards.rename(columns={
    "team": "team_code"}, inplace=True)

In [ ]:
mvp_awards["season_id"] = (
    mvp_awards["season"]
    .map(season_map))

In [ ]:
mvp_awards.shape

(61, 8)

In [ ]:
mvp_award_df = mvp_awards[[
        "player_id",
        "season_id",
        "team_code",
        "mvp_rank",
        "mvp_share"]].copy()

In [ ]:
mvp_awards.head()

,season,mvp_rank,player_id,player_name,player_url,team_code,mvp_share,season_id
0,2019-20,1.0,antetgi01,Giannis Antetokounmpo,/players/a/antetgi01.html,MIL,0.952,1
1,2019-20,2.0,jamesle01,LeBron James,/players/j/jamesle01.html,LAL,0.746,1
2,2019-20,3.0,hardeja01,James Harden,/players/h/hardeja01.html,HOU,0.363,1
3,2019-20,4.0,doncilu01,Luka Dončić,/players/d/doncilu01.html,DAL,0.198,1
4,2019-20,5.0,leonaka01,Kawhi Leonard,/players/l/leonaka01.html,LAC,0.166,1

In [ ]:
mvp_award_df = mvp_award_df.drop(columns=["team_code"])

In [ ]:
mvp_award_df.head()

   player_id  season_id  mvp_rank  mvp_share
0  antetgi01          1       1.0      0.952
1  jamesle01          1       2.0      0.746
2  hardeja01          1       3.0      0.363
3  doncilu01          1       4.0      0.198
4  leonaka01          1       5.0      0.166

In [ ]:
mvp_award_df.isnull().sum()

player_id    0
season_id    0
mvp_rank     8
mvp_share    0
dtype: int64

In [ ]:
mvp_award_df['season_id'].unique()

array([1, 2, 3, 4, 5], dtype=int64)

### champion_team_player DataFrame

In [ ]:
champions.head()

,season,champion_team,team_code,player_id,player_name,player_url,number,position,height,weight,birth_date,birth_place,experience,college,age,games,minutes,win_shares
0,2020-21,Milwaukee Bucks,MIL,adamsja01,Jaylen Adams,https://www.basketball-reference.com/players/a...,6,PG,6-0,225,1996-05-04,us US,2,St. Bonaventure,24,7,18,-0.1
1,2020-21,Milwaukee Bucks,MIL,antetgi01,Giannis Antetokounmpo,https://www.basketball-reference.com/players/a...,34,PF,6-11,243,1994-12-06,gr GR,7,NaN,26,61,2013,10.2
2,2020-21,Milwaukee Bucks,MIL,antetth01,Thanasis Antetokounmpo,https://www.basketball-reference.com/players/a...,43,SF,6-7,219,1992-07-18,gr GR,2,NaN,28,57,551,0.7
3,2020-21,Milwaukee Bucks,MIL,augusdj01,D.J. Augustin,https://www.basketball-reference.com/players/a...,12,PG,5-11,183,1987-11-10,us US,12,Texas,33,57,1129,2.1
4,2020-21,Milwaukee Bucks,MIL,bryanel01,Elijah Bryant,https://www.basketball-reference.com/players/b...,3,SG,6-5,210,1995-04-19,us US,R,"Elon University , BYU",25,1,32,0.0

In [ ]:
champions.shape

(76, 18)

In [ ]:
champions["season_id"] = (
    champions["season"]
    .map(season_map))

In [ ]:
champion_team_player_df = champions[[
        "player_id",
        "season_id",
        "team_code"]].copy()

In [ ]:
champion_team_player_df.drop_duplicates(inplace=True)

In [ ]:
champion_team_player_df.shape

(76, 3)

In [ ]:
champion_team_player_df.head()

   player_id  season_id team_code
0  adamsja01          2       MIL
1  antetgi01          2       MIL
2  antetth01          2       MIL
3  augusdj01          2       MIL
4  bryanel01          2       MIL

# DataBase

In [ ]:
!pip install sqlalchemy --no-deps

Collecting sqlalchemy

WARNING: Ignoring invalid distribution -umpy (f:\anaconda\envs\quera\lib\site-packages)
WARNING: Ignoring invalid distribution -umpy (f:\anaconda\envs\quera\lib\site-packages)

  Using cached sqlalchemy-2.0.51-cp39-cp39-win_amd64.whl.metadata (9.8 kB)
Using cached sqlalchemy-2.0.51-cp39-cp39-win_amd64.whl (2.1 MB)
Installing collected packages: sqlalchemy
Successfully installed sqlalchemy-2.0.51

In [ ]:
!pip install pymysql typing-extensions

Collecting pymysql
  Using cached pymysql-1.2.0-py3-none-any.whl.metadata (4.3 kB)
Requirement already satisfied: typing-extensions in f:\anaconda\envs\quera\lib\site-packages (4.15.0)
Using cached pymysql-1.2.0-py3-none-any.whl (45 kB)
Installing collected packages: pymysql
Successfully installed pymysql-1.2.0

WARNING: Ignoring invalid distribution -umpy (f:\anaconda\envs\quera\lib\site-packages)
WARNING: Ignoring invalid distribution -umpy (f:\anaconda\envs\quera\lib\site-packages)
WARNING: Ignoring invalid distribution -umpy (f:\anaconda\envs\quera\lib\site-packages)

In [ ]:
import sqlalchemy
import pymysql
from sqlalchemy import create_engine
from sqlalchemy import text
from urllib.parse import quote_plus

In [ ]:
USERNAME = "root"
PASSWORD = quote_plus("7272528234sJ*") #encoding the real pass 
HOST = "localhost"
PORT = 3306
DATABASE = "basketball_db"

engine = create_engine(
    f"mysql+pymysql://{USERNAME}:{PASSWORD}@{HOST}:{PORT}/{DATABASE}")

In [ ]:
## in sqlalchemy all raw sql queries must be wrapped in text()

In [ ]:
with engine.connect() as conn:
    print(conn.execute(text("SELECT DATABASE();")).fetchone())

('basketball_db',)

In [ ]:
with engine.connect() as conn:
    result = conn.execute(text("SHOW TABLES"))

    for row in result:
        print(row[0])

championteamplayer
college
country
mvp_award
player
playercollege
playerposition
playerseasonstats
positions
season
team

### country

In [ ]:
country_df.head()

   country_id country_name
0           1           ag
1           2           ao
2           3           ar
3           4           at
4           5           au

In [ ]:
country_df.to_sql(
    name="country",
    con=engine,
    if_exists="append",
    index=False)

93

In [ ]:
#test

In [ ]:
with engine.connect() as conn:
    result = conn.execute(text("SELECT COUNT(*) FROM country"))
    print(result.scalar())

93

### college

In [ ]:
college_df.head()

   college_id            college_name
0           1     1985in College Park
1           2       Acadia University
2           3               Air Force
3           4                 Alabama
4           5  Alabama A&M University

In [ ]:
college_df.shape

(670, 2)

In [ ]:
college_df.to_sql(name="college",
                    con=engine,
                    if_exists="append",
                    index=False)

670

### positions

In [ ]:
position_df

   position_id position_name
0            1             C
1            2             F
2            3             G
3            4            PF
4            5            PG
5            6            SF
6            7            SG

In [ ]:
position_df.to_sql(
    name="positions",
    con=engine,
    if_exists="append",
    index=False)

7

### season

In [ ]:
season_df

   season_id season_name
0          1     2019-20
1          2     2020-21
2          3     2021-22
3          4     2022-23
4          5     2023-24

In [ ]:
season_df.to_sql(name="season",
                con=engine,
                if_exists="append",
                index=False)

5

### team

In [ ]:
team_df.head()

  team_code
0       2TM
1       3TM
2       4TM
3       ATL
4       BOS

In [ ]:
team_df.shape

(33, 1)

In [ ]:
team_df.to_sql(name="team",
    con=engine,
    if_exists="append",
    index=False)

33

### player

In [ ]:
player_df.head()

,player_id,full_name,birth_date,birth_place,height_cm,weight_kg,shoots,player_url,country_id
0,aubucch01,Chet Aubuchon,1916-05-18,"Gary,Indianaus",178,62.0,Right,https://www.basketball-reference.com/players/a...,86
1,willial06,Alondes Williams,1999-06-19,"Milwaukee ,Wisconsinus",193,95.0,Right,https://www.basketball-reference.com/players/w...,86
2,barnhle01,Leo Barnhorst,1924-05-11,"Indianapolis,Indianaus",193,86.0,Right,https://www.basketball-reference.com/players/b...,86
3,morriis01,Isaiah Morris,1969-04-02,"Richmond,Virginiaus",203,103.0,Right,https://www.basketball-reference.com/players/m...,86
4,jacksja01,Jaren Jackson,1967-10-27,"New Orleans,Louisianaus",193,86.0,Right,https://www.basketball-reference.com/players/j...,86

In [ ]:
player_df.shape

(5416, 9)

In [ ]:
player_df.dtypes

player_id              object
full_name              object
birth_date     datetime64[ns]
birth_place            object
height_cm               int64
weight_kg             float64
shoots                 object
player_url             object
country_id              int64
dtype: object

In [ ]:
player_df.to_sql(
    name="player",
    con=engine,
    if_exists="append",
    index=False)

5416

In [ ]:
#test

In [ ]:
with engine.connect() as conn:
    result = conn.execute(text("SELECT COUNT(*) FROM player"))
    print(result.scalar())

5416

### player_college

In [ ]:
player_college_df.head()

   player_id  college_id
0  aubucch01         326
1  willial06         538
2  willial06         407
3  willial06         623
4  barnhle01         398

In [ ]:
player_college_df.shape

(5751, 2)

In [ ]:
player_college_df.to_sql(name="playercollege",
                            con=engine,
                            if_exists="append",
                            index=False)

5751

### player_position

In [ ]:
player_position_df.head()

   player_id  position_id
0  aubucch01            3
1  willial06            7
2  barnhle01            6
3  morriis01            6
4  jacksja01            7

In [ ]:
player_position_df.shape

(7156, 2)

In [ ]:
player_position_df.to_sql(name="playerposition",
                            con=engine,
                            if_exists="append",
                            index=False)

7156

### player_season_stats

In [ ]:
player_season_stats_df.head()

,player_id,season_id,team_code,age,games,games_started,minutes,win_shares,ws_per_48,bpm,vorp
0,hardeja01,1,HOU,30,68,68,2483,13.1,0.254,9.6,7.3
1,lillada01,1,POR,29,66,66,2474,11.6,0.225,7.5,5.9
2,antetgi01,1,MIL,25,63,63,1917,11.1,0.279,11.5,6.6
3,davisan02,1,LAL,26,62,62,2131,11.1,0.250,8.0,5.4
4,goberru01,1,UTA,27,68,68,2333,10.7,0.221,3.6,3.3

In [ ]:
player_season_stats_df.shape

(2785, 11)

In [ ]:
player_season_stats_df.to_sql(name="playerseasonstats",
                                con=engine,
                                if_exists="append",
                                index=False)

2785

### mvp_award

In [ ]:
mvp_award_df.head()

   player_id  season_id  mvp_rank  mvp_share
0  antetgi01          1       1.0      0.952
1  jamesle01          1       2.0      0.746
2  hardeja01          1       3.0      0.363
3  doncilu01          1       4.0      0.198
4  leonaka01          1       5.0      0.166

In [ ]:
mvp_award_df['team_code'].value_counts()

team_code
MIL    5
DAL    5
DEN    5
BOS    4
PHO    4
LAL    4
PHI    4
SAC    3
NYK    3
GSW    3
OKC    3
MIA    2
POR    2
LAC    2
TOT    2
MEM    2
TOR    1
UTA    1
WAS    1
CHI    1
BRK    1
CLE    1
HOU    1
MIN    1
Name: count, dtype: int64

In [ ]:
mvp_award_df.shape

(61, 4)

In [ ]:
mvp_award_df.to_sql(name="mvp_award",
                            con=engine,
                            if_exists="append",
                            index=False)

61

### champion_team_player

In [ ]:
champion_team_player_df.head()

   player_id  season_id team_code
0  adamsja01          2       MIL
1  antetgi01          2       MIL
2  antetth01          2       MIL
3  augusdj01          2       MIL
4  bryanel01          2       MIL

In [ ]:
champion_team_player_df.shape

(76, 3)

In [ ]:
champion_team_player_df.to_sql(name="championteamplayer",
                                con=engine,
                                if_exists="append",
                                index=False)

76