# Downloading HTML files

In [33]:
import requests
from bs4 import BeautifulSoup, Comment
import pandas as pd
import time
from pathlib import Path
import pandas as pd
import os

In [2]:
YEARS = [2020, 2021, 2022, 2023, 2024, 2025, 2026]
PATH = '../Data/raw_html'
PROCESSED_DATA_PATH = '../Data/raw_data'
HEADERS = {
    "User-Agent": (
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
        "AppleWebKit/537.36 (KHTML, like Gecko) "
        "Chrome/150.0.0.0 Safari/537.36"
    )
}

In [3]:
#  html mpv (NBA Awards Voting)
save_folder = Path(os.path.join(PATH, 'awards'))
save_folder.mkdir(parents=True, exist_ok=True)

for year in YEARS:
    url = f"https://www.basketball-reference.com/awards/awards_{year}.html"
    file_path = save_folder / f"awards_{year}.html"

    # اگر فایل قبلاً سالم ذخیره شده، دوباره دانلودش نکن
    if file_path.exists() and file_path.stat().st_size > 0:
        print(f"Skipped: {file_path.name}")
        continue

    try:
        response = requests.get(url, headers=HEADERS, timeout=30)
        response.raise_for_status()

        file_path.write_bytes(response.content)

        print(
            f"Saved: {file_path.name} | "
            f"status={response.status_code} | "
            f"size={file_path.stat().st_size} bytes"
        )

        # فاصله بین درخواست‌ها
        time.sleep(3)

    except requests.RequestException as error:
        print(f"Failed for {year}: {error}")

Skipped: awards_2020.html
Skipped: awards_2021.html
Skipped: awards_2022.html
Skipped: awards_2023.html
Skipped: awards_2024.html
Skipped: awards_2025.html
Skipped: awards_2026.html

In [5]:
#چک کردن اینکه کد ها ذخیره شدن
saved_files = sorted(save_folder.glob("*.html"))

for file in saved_files:
    print(file.name, file.stat().st_size)

awards_2020.html 391068
awards_2021.html 410074
awards_2022.html 378061
awards_2023.html 418980
awards_2024.html 400623
awards_2025.html 383970
awards_2026.html 382563

In [6]:
# html season stats

save_folder = Path(os.path.join(PATH, 'advanced_stats'))
save_folder.mkdir(parents=True, exist_ok=True)


for year in YEARS:
    url = f"https://www.basketball-reference.com/leagues/NBA_{year}_advanced.html"
    file_path = save_folder / f"NBA_{year}_advanced.html"

    if file_path.exists() and file_path.stat().st_size > 0:
        print(f"Skipped: {file_path.name}")
        continue

    try:
        response = requests.get(url, headers=HEADERS, timeout=30)
        response.raise_for_status()

        file_path.write_bytes(response.content)

        print(
            f"Saved: {file_path.name} | "
            f"status={response.status_code} | "
            f"size={file_path.stat().st_size} bytes"
        )

        time.sleep(3)

    except requests.RequestException as error:
        print(f"Failed for {year}: {error}")

Skipped: NBA_2020_advanced.html
Skipped: NBA_2021_advanced.html
Skipped: NBA_2022_advanced.html
Skipped: NBA_2023_advanced.html
Skipped: NBA_2024_advanced.html
Skipped: NBA_2025_advanced.html
Skipped: NBA_2026_advanced.html

In [7]:
#بررسی فایل ها

saved_files = sorted(save_folder.glob("*.html"))

for file in saved_files:
    print(file.name, file.stat().st_size)

NBA_2020_advanced.html 2000829
NBA_2021_advanced.html 2169609
NBA_2022_advanced.html 2352512
NBA_2023_advanced.html 2061890
NBA_2024_advanced.html 2180047
NBA_2025_advanced.html 2191854
NBA_2026_advanced.html 2211021

In [8]:
#تیم های قهرمان html
save_folder = Path(os.path.join(PATH, 'league_summary'))
save_folder.mkdir(parents=True, exist_ok=True)


for year in YEARS:
    url = f"https://www.basketball-reference.com/leagues/NBA_{year}.html"
    file_path = save_folder / f"NBA_{year}.html"

    if file_path.exists() and file_path.stat().st_size > 0:
        print(f"Skipped: {file_path.name}")
        continue

    try:
        response = requests.get(url, headers=HEADERS, timeout=30)
        response.raise_for_status()

        file_path.write_bytes(response.content)

        print(
            f"Saved: {file_path.name} | "
            f"status={response.status_code} | "
            f"size={file_path.stat().st_size} bytes"
        )

        time.sleep(3)

    except requests.RequestException as error:
        print(f"Failed for {year}: {error}")

Skipped: NBA_2020.html
Skipped: NBA_2021.html
Skipped: NBA_2022.html
Skipped: NBA_2023.html
Skipped: NBA_2024.html
Skipped: NBA_2025.html
Skipped: NBA_2026.html

In [9]:
#بررسی
saved_files = sorted(save_folder.glob("*.html"))

for file in saved_files:
    print(file.name, file.stat().st_size)

NBA_2020.html 805629
NBA_2021.html 803461
NBA_2022.html 804930
NBA_2023.html 804202
NBA_2024.html 805986
NBA_2025.html 809010
NBA_2026.html 808453

In [10]:
# html champion team 
save_folder = Path(os.path.join(PATH, 'champion_teams'))
save_folder.mkdir(parents=True, exist_ok=True)

# سال پایان فصل: کد تیم قهرمان
champions = {
    2020: "LAL",  # Los Angeles Lakers — 2019-20
    2021: "MIL",  # Milwaukee Bucks — 2020-21
    2022: "GSW",  # Golden State Warriors — 2021-22
    2023: "DEN",  # Denver Nuggets — 2022-23
    2024: "BOS",  # Boston Celtics — 2023-24
    2025: "OKC",  # Oklahoma City Thunder — 2024-25
    2026: "NYK",  # New York Knicks — 2025-26
}

for year, team_code in champions.items():
    url = (
        f"https://www.basketball-reference.com/"
        f"teams/{team_code}/{year}.html"
    )

    file_path = save_folder / f"{team_code}_{year}.html"

    # اگر فایل قبلاً سالم ذخیره شده، دوباره درخواست نزن
    if file_path.exists() and file_path.stat().st_size > 0:
        print(f"Skipped: {file_path.name}")
        continue

    try:
        response = requests.get(url, headers=HEADERS, timeout=30)
        response.raise_for_status()

        file_path.write_bytes(response.content)

        print(
            f"Saved: {file_path.name} | "
            f"status={response.status_code} | "
            f"size={file_path.stat().st_size} bytes"
        )

        time.sleep(3)

    except requests.RequestException as error:
        print(
            f"Failed: season={year}, team={team_code} | "
            f"{error}"
        )

Skipped: LAL_2020.html
Skipped: MIL_2021.html
Skipped: GSW_2022.html
Skipped: DEN_2023.html
Skipped: BOS_2024.html
Skipped: OKC_2025.html
Skipped: NYK_2026.html

In [11]:
#بررسی
saved_files = sorted(save_folder.glob("*.html"))
for file in saved_files:
    print(file.name, file.stat().st_size)

BOS_2024.html 927615
DEN_2023.html 906885
GSW_2022.html 878802
LAL_2020.html 956668
MIL_2021.html 1005836
NYK_2026.html 949278
OKC_2025.html 923915

# Using BS4 to Scrapping data

In [12]:
SEASONS = {
    2020: "2019-20",
    2021: "2020-21",
    2022: "2021-22",
    2023: "2022-23",
    2024: "2023-24",
    2025: "2024-25",
    2026: "2025-26",
}

output_folder = Path(PROCESSED_DATA_PATH)
output_folder.mkdir(parents=True, exist_ok=True)

## Awards

In [13]:
# for all seasons (mvp)
# پوشه HTMLهای Awards
awards_folder = Path(os.path.join(PATH, 'awards'))

all_mvp_players = []

for year, season in SEASONS.items():

    # 1) مسیر فایل همان فصل
    file_path = awards_folder / f"awards_{year}.html"

    # 2) خواندن HTML ذخیره‌شده
    with open(file_path, "r", encoding="utf-8") as file:
        html = file.read()

    # 3) پارس HTML
    soup = BeautifulSoup(html, "html.parser")

    # 4) پیدا کردن جدول MVP
    mvp_table = soup.find("table", id="mvp")

    if mvp_table is None:
        print(f"MVP table not found for {season}")
        continue

    # 5) گرفتن ردیف‌های بازیکنان
    rows = mvp_table.find("tbody").find_all("tr")

    # 6) استخراج بازیکنان همان فصل
    for row in rows:
        rank_cell = row.find("th", {"data-stat": "rank"})
        player_cell = row.find("td", {"data-stat": "player"})
        team_cell = row.find("td", {"data-stat": "team_id"})
        share_cell = row.find("td", {"data-stat": "award_share"})

        if player_cell is None:
            continue

        player_link_tag = player_cell.find("a")

        player_record = {
            "season": season,
            "mvp_rank": rank_cell.get_text(strip=True) if rank_cell else None,
            "player_id": player_cell.get("data-append-csv"),
            "player_name": player_cell.get_text(strip=True),
            "player_url": player_link_tag.get("href") if player_link_tag else None,
            "team": team_cell.get_text(strip=True) if team_cell else None,
            "mvp_share": share_cell.get_text(strip=True) if share_cell else None
        }

        all_mvp_players.append(player_record)

    print(f"{season}: {len(rows)} rows processed")

2019-20: 12 rows processed
2020-21: 15 rows processed
2021-22: 12 rows processed
2022-23: 13 rows processed
2023-24: 9 rows processed
2024-25: 12 rows processed
2025-26: 8 rows processed

In [14]:
mvp_all_seasons_df = pd.DataFrame(all_mvp_players)

In [15]:
# THIS LINE PREVENT NAN BECAUSE SOME RANK CONTAINS LETTER `T`
mvp_all_seasons_df["mvp_rank"] = (
    mvp_all_seasons_df["mvp_rank"]
    .apply(lambda x: x.replace("T", "") if isinstance(x, str) else x)
)


mvp_all_seasons_df["mvp_rank"] = pd.to_numeric(
    mvp_all_seasons_df["mvp_rank"],
    errors="coerce"
)

mvp_all_seasons_df["mvp_share"] = pd.to_numeric(
    mvp_all_seasons_df["mvp_share"],
    errors="coerce"
)

In [16]:
mvp_all_seasons_df
mvp_all_seasons_df.groupby("season").size()

season
2019-20    12
2020-21    15
2021-22    12
2022-23    13
2023-24     9
2024-25    12
2025-26     8
dtype: int64

In [17]:
output_folder = Path(PROCESSED_DATA_PATH)
output_folder.mkdir(exist_ok=True)

output_path = output_folder / "mvp_all_seasons.csv"

mvp_all_seasons_df.to_csv(
    output_path,
    index=False,
    encoding="utf-8-sig"
)

print(output_path.resolve())

/Users/parsa/Desktop/projects/BOOTCAMP/PROJECT3/Data/raw_data/mvp_all_seasons.csv

In [18]:
mvp_all_seasons_df.isna().sum()

season         0
mvp_rank       0
player_id      0
player_name    0
player_url     0
team           0
mvp_share      0
dtype: int64

## Advance Stats

In [38]:

advanced_folder = Path(os.path.join(PATH, 'advanced_stats'))
output_folder = Path(PROCESSED_DATA_PATH)
output_folder.mkdir(parents=True, exist_ok=True)


# -----------------------------
# پارس یک ردیف بازیکن
# -----------------------------

def parse_player_row(row, season):

    def text(selector):
        element = row.select_one(selector)

        if element is None:
            return None

        return " ".join(
            element.get_text(" ", strip=True).split()
        )

    player_cell = row.select_one(
        'td[data-stat="name_display"], '
        'th[data-stat="name_display"]'
    )

    if player_cell is None:
        return None

    player_link = player_cell.select_one("a")

    player_id = player_cell.get("data-append-csv")

    player_relative_url = (
        player_link.get("href")
        if player_link is not None
        else None
    )

    player_url = (
        f"https://www.basketball-reference.com{player_relative_url}"
        if player_relative_url
        else None
    )

    return {
        "season": season,
        "player_id": player_id,
        "player_name": text(
            'td[data-stat="name_display"], '
            'th[data-stat="name_display"]'
        ),
        "player_url": player_url,
        "age": text('td[data-stat="age"]'),
        "team": text('td[data-stat="team_name_abbr"]'),
        "position": text('td[data-stat="pos"]'),
        "games": text('td[data-stat="games"]'),
        "games_started": text('td[data-stat="games_started"]'),
        "minutes": text('td[data-stat="mp"]'),
        "win_shares": text('td[data-stat="ws"]'),
        "ws_per_48": text('td[data-stat="ws_per_48"]'),
        "bpm": text('td[data-stat="bpm"]'),
        "vorp": text('td[data-stat="vorp"]'),
    }

def find_advanced_table(soup):

    table = soup.select_one("table#advanced")

    if table is not None:
        return table

    comments = soup.find_all(
        string=lambda text: isinstance(text, Comment)
    )

    for comment in comments:

        if 'id="advanced"' not in comment:
            continue

        comment_soup = BeautifulSoup(comment, "html.parser")
        table = comment_soup.select_one("table#advanced")

        if table is not None:
            return table

    return None
# -----------------------------
# استخراج پنج فصل
# -----------------------------

all_advanced_records = []

for year, season in SEASONS.items():

    file_path = advanced_folder / f"NBA_{year}_advanced.html"

    if not file_path.exists():
        print(f"File not found: {file_path}")
        continue

    with open(file_path, "r", encoding="utf-8") as file:
        html = file.read()

    soup = BeautifulSoup(html, "html.parser")

    advanced_table = find_advanced_table(soup)

    if advanced_table is None:
        print(f"Advanced table not found for {season}")
        continue

    rows = advanced_table.select("tbody tr")

    season_count = 0

    for row in rows:
        record = parse_player_row(row, season)

        if record is None:
            continue

        if record["player_id"] is None:
            continue

        all_advanced_records.append(record)
        season_count += 1

    print(f"{season}: {season_count} valid rows extracted")


# -----------------------------
# ساخت DataFrame
# -----------------------------

advanced_raw_df = pd.DataFrame(all_advanced_records)

numeric_columns = [
    "age",
    "games",
    "games_started",
    "minutes",
    "win_shares",
    "ws_per_48",
    "bpm",
    "vorp",
]

for column in numeric_columns:
    advanced_raw_df[column] = pd.to_numeric(
        advanced_raw_df[column],
        errors="coerce"
    )


# -----------------------------
# مدیریت بازیکنان چندتیمی
# -----------------------------

def choose_player_season_row(group):

    team_values = group["team"].fillna("")

    total_team_mask = team_values.str.match(r"^\d+TM$")

    if total_team_mask.any():
        return group.loc[total_team_mask].iloc[0]

    return group.sort_values(
        by=["minutes", "games"],
        ascending=False,
        na_position="last"
    ).iloc[0]


advanced_clean_df = (
    advanced_raw_df
    .groupby(["season", "player_id"], group_keys=True)
    .apply(choose_player_season_row)
    .reset_index()          # brings season & player_id back as columns
)

# -----------------------------
# مرتب‌سازی و کنترل
# -----------------------------

advanced_clean_df = advanced_clean_df.sort_values(
    by=["season", "win_shares"],
    ascending=[True, False],
    na_position="last"
).reset_index(drop=True)

print("\nRaw rows per season:")
print(advanced_raw_df.groupby("season").size())

print("\nUnique players per season:")
print(advanced_clean_df.groupby("season").size())

display(advanced_clean_df.head(10))


# -----------------------------
# ذخیره فایل‌ها
# -----------------------------

raw_path = output_folder / "advanced_stats_all_rows.csv"
clean_path = output_folder / "advanced_stats_all_seasons.csv"

advanced_raw_df.to_csv(
    raw_path,
    index=False,
    encoding="utf-8-sig"
)

advanced_clean_df.to_csv(
    clean_path,
    index=False,
    encoding="utf-8-sig"
)

print("\nSaved raw file:")
print(raw_path.resolve())

print("\nSaved cleaned file:")
print(clean_path.resolve())

2019-20: 651 valid rows extracted
2020-21: 705 valid rows extracted
2021-22: 812 valid rows extracted
2022-23: 679 valid rows extracted
2023-24: 735 valid rows extracted
2024-25: 735 valid rows extracted
2025-26: 733 valid rows extracted

Raw rows per season:
season
2019-20    651
2020-21    705
2021-22    812
2022-23    679
2023-24    735
2024-25    735
2025-26    733
dtype: int64

Unique players per season:
season
2019-20    529
2020-21    540
2021-22    605
2022-23    539
2023-24    572
2024-25    569
2025-26    582
dtype: int64

,season,player_id,player_name,player_url,age,team,position,games,games_started,minutes,win_shares,ws_per_48,bpm,vorp
0,2019-20,hardeja01,James Harden,https://www.basketball-reference.com/players/h...,30,HOU,SG,68,68,2483,13.1,0.254,9.6,7.3
1,2019-20,lillada01,Damian Lillard,https://www.basketball-reference.com/players/l...,29,POR,PG,66,66,2474,11.6,0.225,7.5,5.9
2,2019-20,antetgi01,Giannis Antetokounmpo,https://www.basketball-reference.com/players/a...,25,MIL,PF,63,63,1917,11.1,0.279,11.5,6.6
3,2019-20,davisan02,Anthony Davis,https://www.basketball-reference.com/players/d...,26,LAL,PF,62,62,2131,11.1,0.250,8.0,5.4
4,2019-20,goberru01,Rudy Gobert,https://www.basketball-reference.com/players/g...,27,UTA,C,68,68,2333,10.7,0.221,3.6,3.3
5,2019-20,jamesle01,LeBron James,https://www.basketball-reference.com/players/j...,35,LAL,PG,67,67,2316,9.8,0.204,8.4,6.1
6,2019-20,jokicni01,Nikola Jokić,https://www.basketball-reference.com/players/j...,24,DEN,C,73,73,2336,9.8,0.202,7.4,5.5
7,2019-20,butleji01,Jimmy Butler,https://www.basketball-reference.com/players/b...,30,MIA,SF,58,58,1959,9.0,0.221,5.4,3.7
8,2019-20,paulch01,Chris Paul,https://www.basketball-reference.com/players/p...,34,OKC,PG,70,70,2208,8.9,0.193,4.4,3.5
9,2019-20,doncilu01,Luka Dončić,https://www.basketball-reference.com/players/d...,20,DAL,PG,61,61,2047,8.8,0.207,8.4,5.4

Saved raw file:
/Users/parsa/Desktop/projects/BOOTCAMP/PROJECT3/Data/raw_data/advanced_stats_all_rows.csv

Saved cleaned file:
/Users/parsa/Desktop/projects/BOOTCAMP/PROJECT3/Data/raw_data/advanced_stats_all_seasons.csv

In [42]:
advanced_clean_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3936 entries, 0 to 3935
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   season         3936 non-null   str
 1   player_id      3936 non-null   str
 2   player_name    3936 non-null   str
 3   player_url     3936 non-null   str
 4   age            3936 non-null   int64
 5   team           3936 non-null   str
 6   position       3936 non-null   str
 7   games          3936 non-null   int64
 8   games_started  3936 non-null   int64
 9   minutes        3936 non-null   int64
 10  win_shares     3936 non-null   float64
 11  ws_per_48      3936 non-null   float64
 12  bpm            3936 non-null   float64
 13  vorp           3936 non-null   float64
dtypes: float64(4), int64(4), str(6)
memory usage: 430.6 KB

In [43]:
advanced_raw_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5050 entries, 0 to 5049
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   season         5050 non-null   str
 1   player_id      5050 non-null   str
 2   player_name    5050 non-null   str
 3   player_url     5050 non-null   str
 4   age            5050 non-null   int64
 5   team           5050 non-null   str
 6   position       5050 non-null   str
 7   games          5050 non-null   int64
 8   games_started  5050 non-null   int64
 9   minutes        5050 non-null   int64
 10  win_shares     5050 non-null   float64
 11  ws_per_48      5050 non-null   float64
 12  bpm            5050 non-null   float64
 13  vorp           5050 non-null   float64
dtypes: float64(4), int64(4), str(6)
memory usage: 552.5 KB

## Champion

In [45]:

# --------------------------------
# مسیر فایل‌ها و اطلاعات قهرمانان
# --------------------------------
champion_folder = Path(os.path.join(PATH, 'champion_teams'))
output_folder = Path(PROCESSED_DATA_PATH)
output_folder.mkdir(parents=True, exist_ok=True)

champion_files = [
    {
        "season": "2020-21",
        "champion_team": "Milwaukee Bucks",
        "team_code": "MIL",
        "file_name": "MIL_2021.html",
    },
    {
        "season": "2021-22",
        "champion_team": "Golden State Warriors",
        "team_code": "GSW",
        "file_name": "GSW_2022.html",
    },
    {
        "season": "2022-23",
        "champion_team": "Denver Nuggets",
        "team_code": "DEN",
        "file_name": "DEN_2023.html",
    },
    {
        "season": "2023-24",
        "champion_team": "Boston Celtics",
        "team_code": "BOS",
        "file_name": "BOS_2024.html",
    },
    {
        "season": "2024-25",
        "champion_team": "Oklahoma City Thunder",
        "team_code": "OKC",
        "file_name": "OKC_2025.html",
    },
    {
        "season": "2025-26",
        "champion_team": "New York Knicks",
        "team_code": "NYK",
        "file_name": "NYK_2026.html",
    },
]

# --------------------------------
# تبدیل یک ردیف roster به یک رکورد
# --------------------------------

def parse_roster_row(row, season, champion_team, team_code):

    def txt(data_stat):
        element = row.find(
            ["td", "th"],
            {"data-stat": data_stat},
        )
        if element is None:
            return None
        
        return " ".join(element.get_text(" ", strip=True).split())


    player_cell = row.find(
        ["td", "th"],
        {"data-stat": "player"},
    )

    if player_cell is None:
        return None

    player_link = player_cell.find("a")

    player_id = player_cell.get("data-append-csv")

    # اگر شناسه مستقیماً موجود نبود، از لینک استخراج شود
    if player_id is None and player_link is not None:
        href = player_link.get("href")

        if href:
            player_id = Path(href).stem

    relative_url = (
        player_link.get("href")
        if player_link is not None
        else None
    )

    player_url = (
        f"https://www.basketball-reference.com{relative_url}"
        if relative_url
        else None
    )

    return {
        "season": season,
        "champion_team": champion_team,
        "team_code": team_code,
        "player_id": player_id,
        "player_name": txt("player"),
        "player_url": player_url,
        "number": txt("number"),
        "position": txt("pos"),
        "height": txt("height"),
        "weight": txt("weight"),
        "birth_date": txt("birth_date"),
        "birth_place": txt("flag"),
        "experience": txt("years_experience"),
        "college": txt("college"),
    }


# --------------------------------
# خواندن چهار فایل و استخراج بازیکنان
# --------------------------------

champion_records = []

for champion in champion_files:

    file_path = champion_folder / champion["file_name"]

    if not file_path.exists():
        print(f"File not found: {file_path}")
        continue

    with open(file_path, "r", encoding="utf-8") as file:
        html = file.read()

    soup = BeautifulSoup(html, "html.parser")

    roster_table = soup.find("table", id="roster")

    if roster_table is None:
        print(f"Roster table not found: {champion['season']}")
        continue

    tbody = roster_table.find("tbody")

    if tbody is None:
        print(f"tbody not found: {champion['season']}")
        continue

    rows = tbody.find_all("tr")

    season_count = 0

    for row in rows:
        record = parse_roster_row(
            row=row,
            season=champion["season"],
            champion_team=champion["champion_team"],
            team_code=champion["team_code"],
        )

        if record is None:
            continue

        if record["player_id"] is None:
            continue

        champion_records.append(record)
        season_count += 1

    print(
        f"{champion['season']} | "
        f"{champion['champion_team']}: "
        f"{season_count} players extracted"
    )


# --------------------------------
# ساخت DataFrame
# --------------------------------

champion_roster_df = pd.DataFrame(champion_records)

champion_roster_df["weight"] = pd.to_numeric(
    champion_roster_df["weight"],
    errors="coerce",
)

champion_roster_df["birth_date"] = pd.to_datetime(
    champion_roster_df["birth_date"],
    errors="coerce",
)

print("\nPlayers per champion team:")
print(
    champion_roster_df
    .groupby(["season", "champion_team"])
    .size()
)

display(champion_roster_df.head(10))


# --------------------------------
# اتصال به Advanced برای سن و بازی
# --------------------------------

advanced_for_merge = advanced_clean_df[
    [
        "season",
        "player_id",
        "age",
        "games",
        "minutes",
        "win_shares",
    ]
].copy()

champion_players_df = champion_roster_df.merge(
    advanced_for_merge,
    on=["season", "player_id"],
    how="left",
    validate="one_to_one",
)

print("\nMissing advanced matches:")
print(
    champion_players_df[
        champion_players_df["games"].isna()
    ][
        [
            "season",
            "champion_team",
            "player_name",
            "player_id",
        ]
    ]
)

display(champion_players_df.head(10))


# --------------------------------
# ذخیره خروجی‌ها
# --------------------------------

roster_path = output_folder / "champion_rosters.csv"
final_path = output_folder / "champion_players_all_seasons.csv"

champion_roster_df.to_csv(
    roster_path,
    index=False,
    encoding="utf-8-sig",
)

champion_players_df.to_csv(
    final_path,
    index=False,
    encoding="utf-8-sig",
)

print("\nSaved roster file:")
print(roster_path.resolve())

print("\nSaved merged file:")
print(final_path.resolve())

2020-21 | Milwaukee Bucks: 22 players extracted
2021-22 | Golden State Warriors: 17 players extracted
2022-23 | Denver Nuggets: 18 players extracted
2023-24 | Boston Celtics: 19 players extracted
2024-25 | Oklahoma City Thunder: 19 players extracted
2025-26 | New York Knicks: 20 players extracted

Players per champion team:
season   champion_team
2020-21  Milwaukee Bucks          22
2021-22  Golden State Warriors    17
2022-23  Denver Nuggets           18
2023-24  Boston Celtics           19
2024-25  Oklahoma City Thunder    19
2025-26  New York Knicks          20
dtype: int64

,season,champion_team,team_code,player_id,player_name,player_url,number,position,height,weight,birth_date,birth_place,experience,college
0,2020-21,Milwaukee Bucks,MIL,adamsja01,Jaylen Adams,https://www.basketball-reference.com/players/a...,6,PG,6-0,225,1996-05-04,us US,2,St. Bonaventure
1,2020-21,Milwaukee Bucks,MIL,antetgi01,Giannis Antetokounmpo,https://www.basketball-reference.com/players/a...,34,PF,6-11,243,1994-12-06,gr GR,7,
2,2020-21,Milwaukee Bucks,MIL,antetth01,Thanasis Antetokounmpo,https://www.basketball-reference.com/players/a...,43,SF,6-7,219,1992-07-18,gr GR,2,
3,2020-21,Milwaukee Bucks,MIL,augusdj01,D.J. Augustin,https://www.basketball-reference.com/players/a...,12,PG,5-11,183,1987-11-10,us US,12,Texas
4,2020-21,Milwaukee Bucks,MIL,bryanel01,Elijah Bryant,https://www.basketball-reference.com/players/b...,3,SG,6-5,210,1995-04-19,us US,R,"Elon University , BYU"
5,2020-21,Milwaukee Bucks,MIL,connapa01,Pat Connaughton,https://www.basketball-reference.com/players/c...,24,SG,6-5,209,1993-01-06,us US,5,Notre Dame
6,2020-21,Milwaukee Bucks,MIL,craigto01,Torrey Craig,https://www.basketball-reference.com/players/c...,3,SF,6-5,221,1990-12-19,us US,3,USC Upstate
7,2020-21,Milwaukee Bucks,MIL,diakima01,Mamadi Diakite,https://www.basketball-reference.com/players/d...,25,PF,6-9,228,1997-01-21,gn GN,R,Virginia
8,2020-21,Milwaukee Bucks,MIL,divindo01,Donte DiVincenzo,https://www.basketball-reference.com/players/d...,0,SG,6-4,203,1997-01-31,us US,2,Villanova
9,2020-21,Milwaukee Bucks,MIL,forbebr01,Bryn Forbes,https://www.basketball-reference.com/players/f...,7,SG,6-2,205,1993-07-23,us US,4,Michigan State

Missing advanced matches:
Empty DataFrame
Columns: [season, champion_team, player_name, player_id]
Index: []

,season,champion_team,team_code,player_id,player_name,player_url,number,position,height,weight,birth_date,birth_place,experience,college,age,games,minutes,win_shares
0,2020-21,Milwaukee Bucks,MIL,adamsja01,Jaylen Adams,https://www.basketball-reference.com/players/a...,6,PG,6-0,225,1996-05-04,us US,2,St. Bonaventure,24,7,18,-0.1
1,2020-21,Milwaukee Bucks,MIL,antetgi01,Giannis Antetokounmpo,https://www.basketball-reference.com/players/a...,34,PF,6-11,243,1994-12-06,gr GR,7,,26,61,2013,10.2
2,2020-21,Milwaukee Bucks,MIL,antetth01,Thanasis Antetokounmpo,https://www.basketball-reference.com/players/a...,43,SF,6-7,219,1992-07-18,gr GR,2,,28,57,551,0.7
3,2020-21,Milwaukee Bucks,MIL,augusdj01,D.J. Augustin,https://www.basketball-reference.com/players/a...,12,PG,5-11,183,1987-11-10,us US,12,Texas,33,57,1129,2.1
4,2020-21,Milwaukee Bucks,MIL,bryanel01,Elijah Bryant,https://www.basketball-reference.com/players/b...,3,SG,6-5,210,1995-04-19,us US,R,"Elon University , BYU",25,1,32,0.0
5,2020-21,Milwaukee Bucks,MIL,connapa01,Pat Connaughton,https://www.basketball-reference.com/players/c...,24,SG,6-5,209,1993-01-06,us US,5,Notre Dame,28,69,1575,3.5
6,2020-21,Milwaukee Bucks,MIL,craigto01,Torrey Craig,https://www.basketball-reference.com/players/c...,3,SF,6-5,221,1990-12-19,us US,3,USC Upstate,30,50,803,2.2
7,2020-21,Milwaukee Bucks,MIL,diakima01,Mamadi Diakite,https://www.basketball-reference.com/players/d...,25,PF,6-9,228,1997-01-21,gn GN,R,Virginia,24,14,141,0.3
8,2020-21,Milwaukee Bucks,MIL,divindo01,Donte DiVincenzo,https://www.basketball-reference.com/players/d...,0,SG,6-4,203,1997-01-31,us US,2,Villanova,24,66,1814,3.6
9,2020-21,Milwaukee Bucks,MIL,forbebr01,Bryn Forbes,https://www.basketball-reference.com/players/f...,7,SG,6-2,205,1993-07-23,us US,4,Michigan State,27,70,1354,2.7

Saved roster file:
/Users/parsa/Desktop/projects/BOOTCAMP/PROJECT3/Data/raw_data/champion_rosters.csv

Saved merged file:
/Users/parsa/Desktop/projects/BOOTCAMP/PROJECT3/Data/raw_data/champion_players_all_seasons.csv

In [46]:
champion_roster_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 115 entries, 0 to 114
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   season         115 non-null    str
 1   champion_team  115 non-null    str
 2   team_code      115 non-null    str
 3   player_id      115 non-null    str
 4   player_name    115 non-null    str
 5   player_url     115 non-null    str
 6   number         115 non-null    str
 7   position       115 non-null    str
 8   height         115 non-null    str
 9   weight         115 non-null    int64
 10  birth_date     115 non-null    datetime64[us]
 11  birth_place    115 non-null    str
 12  experience     115 non-null    str
 13  college        115 non-null    str
dtypes: datetime64[us](1), int64(1), str(12)
memory usage: 12.7 KB

In [47]:
champion_players_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 115 entries, 0 to 114
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   season         115 non-null    str
 1   champion_team  115 non-null    str
 2   team_code      115 non-null    str
 3   player_id      115 non-null    str
 4   player_name    115 non-null    str
 5   player_url     115 non-null    str
 6   number         115 non-null    str
 7   position       115 non-null    str
 8   height         115 non-null    str
 9   weight         115 non-null    int64
 10  birth_date     115 non-null    datetime64[us]
 11  birth_place    115 non-null    str
 12  experience     115 non-null    str
 13  college        115 non-null    str
 14  age            115 non-null    int64
 15  games          115 non-null    int64
 16  minutes        115 non-null    int64
 17  win_shares     115 non-null    float64
dtypes: datetime64[us](1), float64(1), int64(4), str(12)
memory usage: 16.3 KB