In [18]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time
from pathlib import Path
import pandas as pd

In [19]:
#  html mpv
save_folder = Path("raw_html/awards")
save_folder.mkdir(parents=True, exist_ok=True)

years = [2020, 2021, 2022, 2023, 2024]

headers = {
    "User-Agent": (
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
        "AppleWebKit/537.36 "
        "Chrome/150.0 Safari/537.36"
    )
}

for year in years:
    url = f"https://www.basketball-reference.com/awards/awards_{year}.html"
    file_path = save_folder / f"awards_{year}.html"

    # اگر فایل قبلاً سالم ذخیره شده، دوباره دانلودش نکن
    if file_path.exists() and file_path.stat().st_size > 0:
        print(f"Skipped: {file_path.name}")
        continue

    try:
        response = requests.get(url, headers=headers, timeout=30)
        response.raise_for_status()

        file_path.write_bytes(response.content)

        print(
            f"Saved: {file_path.name} | "
            f"status={response.status_code} | "
            f"size={file_path.stat().st_size} bytes"
        )

        # فاصله بین درخواست‌ها
        time.sleep(3)

    except requests.RequestException as error:
        print(f"Failed for {year}: {error}")

Skipped: awards_2020.html
Skipped: awards_2021.html
Skipped: awards_2022.html
Skipped: awards_2023.html
Skipped: awards_2024.html

In [20]:
#چک کردن اینکه کد ها ذخیره شدن
saved_files = sorted(save_folder.glob("*.html"))

for file in saved_files:
    print(file.name, file.stat().st_size)

awards_2020.html 391446
awards_2021.html 410452
awards_2022.html 378439
awards_2023.html 419384
awards_2024.html 401027

In [21]:
# html season stats

save_folder = Path("raw_html/advanced_stats")
save_folder.mkdir(parents=True, exist_ok=True)

years = [2020, 2021, 2022, 2023, 2024]

headers = {
    "User-Agent": (
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
        "AppleWebKit/537.36 (KHTML, like Gecko) "
        "Chrome/150.0.0.0 Safari/537.36"
    )
}

for year in years:
    url = f"https://www.basketball-reference.com/leagues/NBA_{year}_advanced.html"
    file_path = save_folder / f"NBA_{year}_advanced.html"

    if file_path.exists() and file_path.stat().st_size > 0:
        print(f"Skipped: {file_path.name}")
        continue

    try:
        response = requests.get(url, headers=headers, timeout=30)
        response.raise_for_status()

        file_path.write_bytes(response.content)

        print(
            f"Saved: {file_path.name} | "
            f"status={response.status_code} | "
            f"size={file_path.stat().st_size} bytes"
        )

        time.sleep(3)

    except requests.RequestException as error:
        print(f"Failed for {year}: {error}")

Skipped: NBA_2020_advanced.html
Skipped: NBA_2021_advanced.html
Skipped: NBA_2022_advanced.html
Skipped: NBA_2023_advanced.html
Skipped: NBA_2024_advanced.html

In [22]:
#بررسی فایل ها

saved_files = sorted(save_folder.glob("*.html"))

for file in saved_files:
    print(file.name, file.stat().st_size)

NBA_2020_advanced.html 2000880
NBA_2021_advanced.html 2169660
NBA_2022_advanced.html 2352563
NBA_2023_advanced.html 2061941
NBA_2024_advanced.html 2180098

In [23]:
#تیم های قهرمان html


save_folder = Path("raw_html/league_summary")
save_folder.mkdir(parents=True, exist_ok=True)

years = [2021, 2022, 2023, 2024]

headers = {
    "User-Agent": (
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
        "AppleWebKit/537.36 (KHTML, like Gecko) "
        "Chrome/150.0.0.0 Safari/537.36"
    )
}

for year in years:
    url = f"https://www.basketball-reference.com/leagues/NBA_{year}.html"
    file_path = save_folder / f"NBA_{year}.html"

    if file_path.exists() and file_path.stat().st_size > 0:
        print(f"Skipped: {file_path.name}")
        continue

    try:
        response = requests.get(url, headers=headers, timeout=30)
        response.raise_for_status()

        file_path.write_bytes(response.content)

        print(
            f"Saved: {file_path.name} | "
            f"status={response.status_code} | "
            f"size={file_path.stat().st_size} bytes"
        )

        time.sleep(3)

    except requests.RequestException as error:
        print(f"Failed for {year}: {error}")

Skipped: NBA_2021.html
Skipped: NBA_2022.html
Skipped: NBA_2023.html
Skipped: NBA_2024.html

In [24]:
#بررسی
saved_files = sorted(save_folder.glob("*.html"))

for file in saved_files:
    print(file.name, file.stat().st_size)

NBA_2021.html 803954
NBA_2022.html 805423
NBA_2023.html 804695
NBA_2024.html 806505

In [25]:
# html champion team 

save_folder = Path("raw_html/champion_teams")
save_folder.mkdir(parents=True, exist_ok=True)

# سال پایان فصل: کد تیم قهرمان
champions = {
    2021: "MIL",  # Milwaukee Bucks — فصل 2020-21
    2022: "GSW",  # Golden State Warriors — فصل 2021-22
    2023: "DEN",  # Denver Nuggets — فصل 2022-23
    2024: "BOS",  # Boston Celtics — فصل 2023-24
}

headers = {
    "User-Agent": (
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
        "AppleWebKit/537.36 (KHTML, like Gecko) "
        "Chrome/150.0.0.0 Safari/537.36"
    )
}

for year, team_code in champions.items():
    url = (
        f"https://www.basketball-reference.com/"
        f"teams/{team_code}/{year}.html"
    )

    file_path = save_folder / f"{team_code}_{year}.html"

    # اگر فایل قبلاً سالم ذخیره شده، دوباره درخواست نزن
    if file_path.exists() and file_path.stat().st_size > 0:
        print(f"Skipped: {file_path.name}")
        continue

    try:
        response = requests.get(url, headers=headers, timeout=30)
        response.raise_for_status()

        file_path.write_bytes(response.content)

        print(
            f"Saved: {file_path.name} | "
            f"status={response.status_code} | "
            f"size={file_path.stat().st_size} bytes"
        )

        time.sleep(3)

    except requests.RequestException as error:
        print(
            f"Failed: season={year}, team={team_code} | "
            f"{error}"
        )

Skipped: MIL_2021.html
Skipped: GSW_2022.html
Skipped: DEN_2023.html
Skipped: BOS_2024.html

In [26]:
#بررسی
saved_files = sorted(save_folder.glob("*.html"))
for file in saved_files:
    print(file.name, file.stat().st_size)

BOS_2024.html 928147
DEN_2023.html 907417
GSW_2022.html 879334
MIL_2021.html 1006368

In [27]:
#beuatiful soup for awards

file_path = Path("raw_html/awards/awards_2020.html")
with open(file_path, "r", encoding="utf-8") as file:
    html = file.read()

soup = BeautifulSoup(html, "html.parser")   
mvp_table = soup.find("table", id="mvp")
mvp_table is None
tbody = mvp_table.find("tbody")
rows = tbody.find_all("tr") 
len(rows)
row = rows[0]
#سلول های مورد نیاز
rank_cell = row.find("th", {"data-stat": "rank"})
player_cell = row.find("td", {"data-stat": "player"})
team_cell = row.find("td", {"data-stat": "team_id"})
share_cell = row.find("td", {"data-stat": "award_share"})
mvp_rank = rank_cell.get_text(strip=True)
#اطلاعات اولین بازیکن
player_name = player_cell.get_text(strip=True)
player_id = player_cell.get("data-append-csv")

player_link_tag = player_cell.find("a")
player_url = player_link_tag.get("href")

team = team_cell.get_text(strip=True)
mvp_share = share_cell.get_text(strip=True)
print(mvp_rank)
print(player_name)
print(player_id)
print(player_url)
print(team)
print(mvp_share)
#رکورد یک بازیکن
player_record = {
    "season": "2019-20",
    "mvp_rank": mvp_rank,
    "player_id": player_id,
    "player_name": player_name,
    "player_url": player_url,
    "team": team,
    "mvp_share": mvp_share
}
player_record
#حلقه روی همه ی بازیکن ها
players_2020 = []

for row in rows:
    rank_cell = row.find("th", {"data-stat": "rank"})
    player_cell = row.find("td", {"data-stat": "player"})
    team_cell = row.find("td", {"data-stat": "team_id"})
    share_cell = row.find("td", {"data-stat": "award_share"})

    # اگر ردیف واقعی بازیکن نبود، ردش کن
    if player_cell is None:
        continue

    player_link_tag = player_cell.find("a")

    player_record = {
        "season": "2019-20",
        "mvp_rank": rank_cell.get_text(strip=True) if rank_cell else None,
        "player_id": player_cell.get("data-append-csv"),
        "player_name": player_cell.get_text(strip=True),
        "player_url": player_link_tag.get("href") if player_link_tag else None,
        "team": team_cell.get_text(strip=True) if team_cell else None,
        "mvp_share": share_cell.get_text(strip=True) if share_cell else None
    }

    players_2020.append(player_record)
    len(players_2020)
    players_2020[:3]

1
Giannis Antetokounmpo
antetgi01
/players/a/antetgi01.html
MIL
0.952

In [28]:
#df
mvp_2020_df = pd.DataFrame(players_2020)
mvp_2020_df
mvp_2020_df["mvp_rank"] = pd.to_numeric(
    mvp_2020_df["mvp_rank"],
    errors="coerce"
)

mvp_2020_df["mvp_share"] = pd.to_numeric(
    mvp_2020_df["mvp_share"],
    errors="coerce"
)
mvp_2020_df.dtypes
output_folder = Path("processed_data")
output_folder.mkdir(exist_ok=True)

mvp_2020_df.to_csv(
    output_folder / "mvp_2019_20.csv",
    index=False,
    encoding="utf-8-sig"
)
(output_folder / "mvp_2019_20.csv").resolve()

WindowsPath('D:/python/first project/processed_data/mvp_2019_20.csv')

In [29]:
# for all seasons (mvp)
# پوشه HTMLهای Awards
awards_folder = Path("raw_html/awards")

seasons = {
    2020: "2019-20",
    2021: "2020-21",
    2022: "2021-22",
    2023: "2022-23",
    2024: "2023-24"
}

all_mvp_players = []

for year, season in seasons.items():

    # 1) مسیر فایل همان فصل
    file_path = awards_folder / f"awards_{year}.html"

    # 2) خواندن HTML ذخیره‌شده
    with open(file_path, "r", encoding="utf-8") as file:
        html = file.read()

    # 3) پارس HTML
    soup = BeautifulSoup(html, "html.parser")

    # 4) پیدا کردن جدول MVP
    mvp_table = soup.find("table", id="mvp")

    if mvp_table is None:
        print(f"MVP table not found for {season}")
        continue

    # 5) گرفتن ردیف‌های بازیکنان
    rows = mvp_table.find("tbody").find_all("tr")

    # 6) استخراج بازیکنان همان فصل
    for row in rows:
        rank_cell = row.find("th", {"data-stat": "rank"})
        player_cell = row.find("td", {"data-stat": "player"})
        team_cell = row.find("td", {"data-stat": "team_id"})
        share_cell = row.find("td", {"data-stat": "award_share"})

        if player_cell is None:
            continue

        player_link_tag = player_cell.find("a")

        player_record = {
            "season": season,
            "mvp_rank": rank_cell.get_text(strip=True) if rank_cell else None,
            "player_id": player_cell.get("data-append-csv"),
            "player_name": player_cell.get_text(strip=True),
            "player_url": player_link_tag.get("href") if player_link_tag else None,
            "team": team_cell.get_text(strip=True) if team_cell else None,
            "mvp_share": share_cell.get_text(strip=True) if share_cell else None
        }

        all_mvp_players.append(player_record)

    print(f"{season}: {len(rows)} rows processed")

2019-20: 12 rows processed
2020-21: 15 rows processed
2021-22: 12 rows processed
2022-23: 13 rows processed
2023-24: 9 rows processed

In [30]:
mvp_all_seasons_df = pd.DataFrame(all_mvp_players)

In [31]:
mvp_all_seasons_df["mvp_rank"] = pd.to_numeric(
    mvp_all_seasons_df["mvp_rank"],
    errors="coerce"
)

mvp_all_seasons_df["mvp_share"] = pd.to_numeric(
    mvp_all_seasons_df["mvp_share"],
    errors="coerce"
)

In [32]:
mvp_all_seasons_df
mvp_all_seasons_df.groupby("season").size()

season
2019-20    12
2020-21    15
2021-22    12
2022-23    13
2023-24     9
dtype: int64

In [33]:
output_folder = Path("processed_data")
output_folder.mkdir(exist_ok=True)

output_path = output_folder / "mvp_all_seasons.csv"

mvp_all_seasons_df.to_csv(
    output_path,
    index=False,
    encoding="utf-8-sig"
)

print(output_path.resolve())

D:\python\first project\processed_data\mvp_all_seasons.csv

In [34]:
#advance_stats
# -----------------------------
# مسیرها و فصل‌ها
# -----------------------------

advanced_folder = Path("raw_html/advanced_stats")
output_folder = Path("processed_data")
output_folder.mkdir(parents=True, exist_ok=True)

seasons = {
    2020: "2019-20",
    2021: "2020-21",
    2022: "2021-22",
    2023: "2022-23",
    2024: "2023-24",
}


# -----------------------------
# پیدا کردن جدول Advanced
# -----------------------------

advanced_table = soup.select_one("table#advanced")
rows = advanced_table.select("tbody tr")


# -----------------------------
# پارس یک ردیف بازیکن
# -----------------------------

def parse_player_row(row, season):

    def text(selector):
        element = row.select_one(selector)

        if element is None:
            return None

        return " ".join(
            element.get_text(" ", strip=True).split()
        )

    player_cell = row.select_one(
        'td[data-stat="name_display"], '
        'th[data-stat="name_display"]'
    )

    if player_cell is None:
        return None

    player_link = player_cell.select_one("a")

    player_id = player_cell.get("data-append-csv")

    player_relative_url = (
        player_link.get("href")
        if player_link is not None
        else None
    )

    player_url = (
        f"https://www.basketball-reference.com{player_relative_url}"
        if player_relative_url
        else None
    )

    return {
        "season": season,
        "player_id": player_id,
        "player_name": text(
            'td[data-stat="name_display"], '
            'th[data-stat="name_display"]'
        ),
        "player_url": player_url,
        "age": text('td[data-stat="age"]'),
        "team": text('td[data-stat="team_name_abbr"]'),
        "position": text('td[data-stat="pos"]'),
        "games": text('td[data-stat="games"]'),
        "games_started": text('td[data-stat="games_started"]'),
        "minutes": text('td[data-stat="mp"]'),
        "win_shares": text('td[data-stat="ws"]'),
        "ws_per_48": text('td[data-stat="ws_per_48"]'),
        "bpm": text('td[data-stat="bpm"]'),
        "vorp": text('td[data-stat="vorp"]'),
    }


# -----------------------------
# استخراج پنج فصل
# -----------------------------

all_advanced_records = []

for year, season in seasons.items():

    file_path = advanced_folder / f"NBA_{year}_advanced.html"

    if not file_path.exists():
        print(f"File not found: {file_path}")
        continue

    with open(file_path, "r", encoding="utf-8") as file:
        html = file.read()

    soup = BeautifulSoup(html, "html.parser")

    advanced_table = find_advanced_table(soup)

    if advanced_table is None:
        print(f"Advanced table not found for {season}")
        continue

    rows = advanced_table.select("tbody tr")

    season_count = 0

    for row in rows:
        record = parse_player_row(row, season)

        if record is None:
            continue

        if record["player_id"] is None:
            continue

        all_advanced_records.append(record)
        season_count += 1

    print(f"{season}: {season_count} valid rows extracted")


# -----------------------------
# ساخت DataFrame
# -----------------------------

advanced_raw_df = pd.DataFrame(all_advanced_records)

numeric_columns = [
    "age",
    "games",
    "games_started",
    "minutes",
    "win_shares",
    "ws_per_48",
    "bpm",
    "vorp",
]

for column in numeric_columns:
    advanced_raw_df[column] = pd.to_numeric(
        advanced_raw_df[column],
        errors="coerce"
    )


# -----------------------------
# مدیریت بازیکنان چندتیمی
# -----------------------------

def choose_player_season_row(group):

    team_values = group["team"].fillna("")

    total_team_mask = team_values.str.match(r"^\d+TM$")

    if total_team_mask.any():
        return group.loc[total_team_mask].iloc[0]

    return group.sort_values(
        by=["minutes", "games"],
        ascending=False,
        na_position="last"
    ).iloc[0]


advanced_clean_df = (
    advanced_raw_df
    .groupby(
        ["season", "player_id"],
        group_keys=False
    )
    .apply(choose_player_season_row)
    .reset_index(drop=True)
)


# -----------------------------
# مرتب‌سازی و کنترل
# -----------------------------

advanced_clean_df = advanced_clean_df.sort_values(
    by=["season", "win_shares"],
    ascending=[True, False],
    na_position="last"
).reset_index(drop=True)

print("\nRaw rows per season:")
print(advanced_raw_df.groupby("season").size())

print("\nUnique players per season:")
print(advanced_clean_df.groupby("season").size())

display(advanced_clean_df.head(10))


# -----------------------------
# ذخیره فایل‌ها
# -----------------------------

raw_path = output_folder / "advanced_stats_all_rows.csv"
clean_path = output_folder / "advanced_stats_all_seasons.csv"

advanced_raw_df.to_csv(
    raw_path,
    index=False,
    encoding="utf-8-sig"
)

advanced_clean_df.to_csv(
    clean_path,
    index=False,
    encoding="utf-8-sig"
)

print("\nSaved raw file:")
print(raw_path.resolve())

print("\nSaved cleaned file:")
print(clean_path.resolve())

AttributeError: 'NoneType' object has no attribute 'select'

In [ ]:
#champion_team

file_path = Path("raw_html/champion_teams/BOS_2024.html")

with open(file_path, "r", encoding="utf-8") as file:
    html = file.read()

soup = BeautifulSoup(html, "html.parser")

In [ ]:
roster_table = soup.find("table", id="roster")

In [ ]:
rows = roster_table.find("tbody").find_all("tr")

print(len(rows))

19

In [ ]:

# --------------------------------
# مسیر فایل‌ها و اطلاعات قهرمانان
# --------------------------------

champion_folder = Path("raw_html/champion_teams")
output_folder = Path("processed_data")
output_folder.mkdir(parents=True, exist_ok=True)

champion_files = [
    {
        "season": "2020-21",
        "champion_team": "Milwaukee Bucks",
        "team_code": "MIL",
        "file_name": "MIL_2021.html",
    },
    {
        "season": "2021-22",
        "champion_team": "Golden State Warriors",
        "team_code": "GSW",
        "file_name": "GSW_2022.html",
    },
    {
        "season": "2022-23",
        "champion_team": "Denver Nuggets",
        "team_code": "DEN",
        "file_name": "DEN_2023.html",
    },
    {
        "season": "2023-24",
        "champion_team": "Boston Celtics",
        "team_code": "BOS",
        "file_name": "BOS_2024.html",
    },
]


# --------------------------------
# تبدیل یک ردیف roster به یک رکورد
# --------------------------------

def parse_roster_row(row, season, champion_team, team_code):

    def txt(data_stat):
        element = row.find(
            ["td", "th"],
            {"data-stat": data_stat},
        )

        if element is None:
            return None

        return " ".join(element.get_text(" ", strip=True).split())

    player_cell = row.find(
        ["td", "th"],
        {"data-stat": "player"},
    )

    if player_cell is None:
        return None

    player_link = player_cell.find("a")

    player_id = player_cell.get("data-append-csv")

    # اگر شناسه مستقیماً موجود نبود، از لینک استخراج شود
    if player_id is None and player_link is not None:
        href = player_link.get("href")

        if href:
            player_id = Path(href).stem

    relative_url = (
        player_link.get("href")
        if player_link is not None
        else None
    )

    player_url = (
        f"https://www.basketball-reference.com{relative_url}"
        if relative_url
        else None
    )

    return {
        "season": season,
        "champion_team": champion_team,
        "team_code": team_code,
        "player_id": player_id,
        "player_name": txt("player"),
        "player_url": player_url,
        "number": txt("number"),
        "position": txt("pos"),
        "height": txt("height"),
        "weight": txt("weight"),
        "birth_date": txt("birth_date"),
        "birth_place": txt("flag"),
        "experience": txt("years_experience"),
        "college": txt("college"),
    }


# --------------------------------
# خواندن چهار فایل و استخراج بازیکنان
# --------------------------------

champion_records = []

for champion in champion_files:

    file_path = champion_folder / champion["file_name"]

    if not file_path.exists():
        print(f"File not found: {file_path}")
        continue

    with open(file_path, "r", encoding="utf-8") as file:
        html = file.read()

    soup = BeautifulSoup(html, "html.parser")

    roster_table = soup.find("table", id="roster")

    if roster_table is None:
        print(f"Roster table not found: {champion['season']}")
        continue

    tbody = roster_table.find("tbody")

    if tbody is None:
        print(f"tbody not found: {champion['season']}")
        continue

    rows = tbody.find_all("tr")

    season_count = 0

    for row in rows:
        record = parse_roster_row(
            row=row,
            season=champion["season"],
            champion_team=champion["champion_team"],
            team_code=champion["team_code"],
        )

        if record is None:
            continue

        if record["player_id"] is None:
            continue

        champion_records.append(record)
        season_count += 1

    print(
        f"{champion['season']} | "
        f"{champion['champion_team']}: "
        f"{season_count} players extracted"
    )


# --------------------------------
# ساخت DataFrame
# --------------------------------

champion_roster_df = pd.DataFrame(champion_records)

champion_roster_df["weight"] = pd.to_numeric(
    champion_roster_df["weight"],
    errors="coerce",
)

champion_roster_df["birth_date"] = pd.to_datetime(
    champion_roster_df["birth_date"],
    errors="coerce",
)

print("\nPlayers per champion team:")
print(
    champion_roster_df
    .groupby(["season", "champion_team"])
    .size()
)

display(champion_roster_df.head(10))


# --------------------------------
# اتصال به Advanced برای سن و بازی
# --------------------------------

advanced_for_merge = advanced_clean_df[
    [
        "season",
        "player_id",
        "age",
        "games",
        "minutes",
        "win_shares",
    ]
].copy()

champion_players_df = champion_roster_df.merge(
    advanced_for_merge,
    on=["season", "player_id"],
    how="left",
    validate="one_to_one",
)

print("\nMissing advanced matches:")
print(
    champion_players_df[
        champion_players_df["games"].isna()
    ][
        [
            "season",
            "champion_team",
            "player_name",
            "player_id",
        ]
    ]
)

display(champion_players_df.head(10))


# --------------------------------
# ذخیره خروجی‌ها
# --------------------------------

roster_path = output_folder / "champion_rosters.csv"
final_path = output_folder / "champion_players_all_seasons.csv"

champion_roster_df.to_csv(
    roster_path,
    index=False,
    encoding="utf-8-sig",
)

champion_players_df.to_csv(
    final_path,
    index=False,
    encoding="utf-8-sig",
)

print("\nSaved roster file:")
print(roster_path.resolve())

print("\nSaved merged file:")
print(final_path.resolve())

2020-21 | Milwaukee Bucks: 22 players extracted
2021-22 | Golden State Warriors: 17 players extracted
2022-23 | Denver Nuggets: 18 players extracted
2023-24 | Boston Celtics: 19 players extracted

Players per champion team:
season   champion_team
2020-21  Milwaukee Bucks          22
2021-22  Golden State Warriors    17
2022-23  Denver Nuggets           18
2023-24  Boston Celtics           19
dtype: int64

,season,champion_team,team_code,player_id,player_name,player_url,number,position,height,weight,birth_date,birth_place,experience,college
0,2020-21,Milwaukee Bucks,MIL,adamsja01,Jaylen Adams,https://www.basketball-reference.com/players/a...,6,PG,6-0,225,1996-05-04,us US,2,St. Bonaventure
1,2020-21,Milwaukee Bucks,MIL,antetgi01,Giannis Antetokounmpo,https://www.basketball-reference.com/players/a...,34,PF,6-11,243,1994-12-06,gr GR,7,
2,2020-21,Milwaukee Bucks,MIL,antetth01,Thanasis Antetokounmpo,https://www.basketball-reference.com/players/a...,43,SF,6-7,219,1992-07-18,gr GR,2,
3,2020-21,Milwaukee Bucks,MIL,augusdj01,D.J. Augustin,https://www.basketball-reference.com/players/a...,12,PG,5-11,183,1987-11-10,us US,12,Texas
4,2020-21,Milwaukee Bucks,MIL,bryanel01,Elijah Bryant,https://www.basketball-reference.com/players/b...,3,SG,6-5,210,1995-04-19,us US,R,"Elon University , BYU"
5,2020-21,Milwaukee Bucks,MIL,connapa01,Pat Connaughton,https://www.basketball-reference.com/players/c...,24,SG,6-5,209,1993-01-06,us US,5,Notre Dame
6,2020-21,Milwaukee Bucks,MIL,craigto01,Torrey Craig,https://www.basketball-reference.com/players/c...,3,SF,6-5,221,1990-12-19,us US,3,USC Upstate
7,2020-21,Milwaukee Bucks,MIL,diakima01,Mamadi Diakite,https://www.basketball-reference.com/players/d...,25,PF,6-9,228,1997-01-21,gn GN,R,Virginia
8,2020-21,Milwaukee Bucks,MIL,divindo01,Donte DiVincenzo,https://www.basketball-reference.com/players/d...,0,SG,6-4,203,1997-01-31,us US,2,Villanova
9,2020-21,Milwaukee Bucks,MIL,forbebr01,Bryn Forbes,https://www.basketball-reference.com/players/f...,7,SG,6-2,205,1993-07-23,us US,4,Michigan State

Missing advanced matches:
Empty DataFrame
Columns: [season, champion_team, player_name, player_id]
Index: []

,season,champion_team,team_code,player_id,player_name,player_url,number,position,height,weight,birth_date,birth_place,experience,college,age,games,minutes,win_shares
0,2020-21,Milwaukee Bucks,MIL,adamsja01,Jaylen Adams,https://www.basketball-reference.com/players/a...,6,PG,6-0,225,1996-05-04,us US,2,St. Bonaventure,24,7,18,-0.1
1,2020-21,Milwaukee Bucks,MIL,antetgi01,Giannis Antetokounmpo,https://www.basketball-reference.com/players/a...,34,PF,6-11,243,1994-12-06,gr GR,7,,26,61,2013,10.2
2,2020-21,Milwaukee Bucks,MIL,antetth01,Thanasis Antetokounmpo,https://www.basketball-reference.com/players/a...,43,SF,6-7,219,1992-07-18,gr GR,2,,28,57,551,0.7
3,2020-21,Milwaukee Bucks,MIL,augusdj01,D.J. Augustin,https://www.basketball-reference.com/players/a...,12,PG,5-11,183,1987-11-10,us US,12,Texas,33,57,1129,2.1
4,2020-21,Milwaukee Bucks,MIL,bryanel01,Elijah Bryant,https://www.basketball-reference.com/players/b...,3,SG,6-5,210,1995-04-19,us US,R,"Elon University , BYU",25,1,32,0.0
5,2020-21,Milwaukee Bucks,MIL,connapa01,Pat Connaughton,https://www.basketball-reference.com/players/c...,24,SG,6-5,209,1993-01-06,us US,5,Notre Dame,28,69,1575,3.5
6,2020-21,Milwaukee Bucks,MIL,craigto01,Torrey Craig,https://www.basketball-reference.com/players/c...,3,SF,6-5,221,1990-12-19,us US,3,USC Upstate,30,50,803,2.2
7,2020-21,Milwaukee Bucks,MIL,diakima01,Mamadi Diakite,https://www.basketball-reference.com/players/d...,25,PF,6-9,228,1997-01-21,gn GN,R,Virginia,24,14,141,0.3
8,2020-21,Milwaukee Bucks,MIL,divindo01,Donte DiVincenzo,https://www.basketball-reference.com/players/d...,0,SG,6-4,203,1997-01-31,us US,2,Villanova,24,66,1814,3.6
9,2020-21,Milwaukee Bucks,MIL,forbebr01,Bryn Forbes,https://www.basketball-reference.com/players/f...,7,SG,6-2,205,1993-07-23,us US,4,Michigan State,27,70,1354,2.7

Saved roster file:
D:\python\first project\basketball-step1\processed_data\champion_rosters.csv

Saved merged file:
D:\python\first project\basketball-step1\processed_data\champion_players_all_seasons.csv